module Moonbase
  module Models
    type activity =
      Moonbase::ActivityCallOccurred
      | Moonbase::ActivityFormSubmitted
      | Moonbase::ActivityInboxMessageSent
      | Moonbase::ActivityItemCreated
      | Moonbase::ActivityItemMentioned
      | Moonbase::ActivityItemMerged
      | Moonbase::Activity::ActivityFileCreated
      | Moonbase::ActivityMeetingHeld
      | Moonbase::ActivityMeetingScheduled
      | Moonbase::ActivityNoteCreated
      | Moonbase::ActivityProgramMessageBounced
      | Moonbase::ActivityProgramMessageClicked
      | Moonbase::ActivityProgramMessageComplained
      | Moonbase::ActivityProgramMessageFailed
      | Moonbase::ActivityProgramMessageOpened
      | Moonbase::ActivityProgramMessageSent
      | Moonbase::ActivityProgramMessageShielded
      | Moonbase::ActivityProgramMessageUnsubscribed

    module Activity
      extend Moonbase::Internal::Type::Union

      type activity_file_created =
        {
          id: String,
          file: Moonbase::Pointer?,
          occurred_at: Time,
          related_item: Moonbase::ItemPointer?,
          type: :"activity/file_created"
        }

      class ActivityFileCreated < Moonbase::Internal::Type::BaseModel
        attr_accessor id: String

        attr_accessor file: Moonbase::Pointer?

        attr_accessor occurred_at: Time

        attr_accessor related_item: Moonbase::ItemPointer?

        attr_accessor type: :"activity/file_created"

        def initialize: (
          id: String,
          file: Moonbase::Pointer?,
          occurred_at: Time,
          related_item: Moonbase::ItemPointer?,
          ?type: :"activity/file_created"
        ) -> void

        def to_hash: -> {
          id: String,
          file: Moonbase::Pointer?,
          occurred_at: Time,
          related_item: Moonbase::ItemPointer?,
          type: :"activity/file_created"
        }
      end

      def self?.variants: -> ::Array[Moonbase::Models::activity]
    end
  end
end
