module Moonbase
  module Models
    type activity =
      Moonbase::Activity::ActivityCallOccurred
      | Moonbase::Activity::ActivityFormSubmitted
      | Moonbase::Activity::ActivityInboxMessageSent
      | Moonbase::Activity::ActivityItemCreated
      | Moonbase::Activity::ActivityItemMentioned
      | Moonbase::Activity::ActivityMeetingHeld
      | Moonbase::Activity::ActivityMeetingScheduled
      | Moonbase::Activity::ActivityNoteCreated
      | Moonbase::Activity::ActivityProgramMessageBounced
      | Moonbase::Activity::ActivityProgramMessageClicked
      | Moonbase::Activity::ActivityProgramMessageComplained
      | Moonbase::Activity::ActivityProgramMessageFailed
      | Moonbase::Activity::ActivityProgramMessageOpened
      | Moonbase::Activity::ActivityProgramMessageSent
      | Moonbase::Activity::ActivityProgramMessageShielded
      | Moonbase::Activity::ActivityProgramMessageUnsubscribed

    module Activity
      extend Moonbase::Internal::Type::Union

      type activity_call_occurred =
        {
          id: String,
          links: Moonbase::Activity::ActivityCallOccurred::Links,
          occurred_at: Time,
          type: :"activity/call_occurred",
          call: Moonbase::Call
        }

      class ActivityCallOccurred < Moonbase::Internal::Type::BaseModel
        attr_accessor id: String

        attr_accessor links: Moonbase::Activity::ActivityCallOccurred::Links

        attr_accessor occurred_at: Time

        attr_accessor type: :"activity/call_occurred"

        attr_reader call: Moonbase::Call?

        def call=: (Moonbase::Call) -> Moonbase::Call

        def initialize: (
          id: String,
          links: Moonbase::Activity::ActivityCallOccurred::Links,
          occurred_at: Time,
          ?call: Moonbase::Call,
          ?type: :"activity/call_occurred"
        ) -> void

        def to_hash: -> {
          id: String,
          links: Moonbase::Activity::ActivityCallOccurred::Links,
          occurred_at: Time,
          type: :"activity/call_occurred",
          call: Moonbase::Call
        }

        type links = { self_: String }

        class Links < Moonbase::Internal::Type::BaseModel
          attr_accessor self_: String

          def initialize: (self_: String) -> void

          def to_hash: -> { self_: String }
        end
      end

      type activity_form_submitted =
        {
          id: String,
          links: Moonbase::Activity::ActivityFormSubmitted::Links,
          occurred_at: Time,
          type: :"activity/form_submitted",
          collection: Moonbase::Collection,
          item: Moonbase::Item
        }

      class ActivityFormSubmitted < Moonbase::Internal::Type::BaseModel
        attr_accessor id: String

        attr_accessor links: Moonbase::Activity::ActivityFormSubmitted::Links

        attr_accessor occurred_at: Time

        attr_accessor type: :"activity/form_submitted"

        attr_reader collection: Moonbase::Collection?

        def collection=: (Moonbase::Collection) -> Moonbase::Collection

        attr_reader item: Moonbase::Item?

        def item=: (Moonbase::Item) -> Moonbase::Item

        def initialize: (
          id: String,
          links: Moonbase::Activity::ActivityFormSubmitted::Links,
          occurred_at: Time,
          ?collection: Moonbase::Collection,
          ?item: Moonbase::Item,
          ?type: :"activity/form_submitted"
        ) -> void

        def to_hash: -> {
          id: String,
          links: Moonbase::Activity::ActivityFormSubmitted::Links,
          occurred_at: Time,
          type: :"activity/form_submitted",
          collection: Moonbase::Collection,
          item: Moonbase::Item
        }

        type links = { self_: String, collection: String, item: String }

        class Links < Moonbase::Internal::Type::BaseModel
          attr_accessor self_: String

          attr_reader collection: String?

          def collection=: (String) -> String

          attr_reader item: String?

          def item=: (String) -> String

          def initialize: (
            self_: String,
            ?collection: String,
            ?item: String
          ) -> void

          def to_hash: -> { self_: String, collection: String, item: String }
        end
      end

      type activity_inbox_message_sent =
        {
          id: String,
          links: Moonbase::Activity::ActivityInboxMessageSent::Links,
          occurred_at: Time,
          type: :"activity/inbox_message_sent",
          message: Moonbase::EmailMessage,
          recipients: ::Array[Moonbase::Address],
          sender: Moonbase::Address
        }

      class ActivityInboxMessageSent < Moonbase::Internal::Type::BaseModel
        attr_accessor id: String

        attr_accessor links: Moonbase::Activity::ActivityInboxMessageSent::Links

        attr_accessor occurred_at: Time

        attr_accessor type: :"activity/inbox_message_sent"

        attr_reader message: Moonbase::EmailMessage?

        def message=: (Moonbase::EmailMessage) -> Moonbase::EmailMessage

        attr_reader recipients: ::Array[Moonbase::Address]?

        def recipients=: (
          ::Array[Moonbase::Address]
        ) -> ::Array[Moonbase::Address]

        attr_reader sender: Moonbase::Address?

        def sender=: (Moonbase::Address) -> Moonbase::Address

        def initialize: (
          id: String,
          links: Moonbase::Activity::ActivityInboxMessageSent::Links,
          occurred_at: Time,
          ?message: Moonbase::EmailMessage,
          ?recipients: ::Array[Moonbase::Address],
          ?sender: Moonbase::Address,
          ?type: :"activity/inbox_message_sent"
        ) -> void

        def to_hash: -> {
          id: String,
          links: Moonbase::Activity::ActivityInboxMessageSent::Links,
          occurred_at: Time,
          type: :"activity/inbox_message_sent",
          message: Moonbase::EmailMessage,
          recipients: ::Array[Moonbase::Address],
          sender: Moonbase::Address
        }

        type links = { self_: String, message: String }

        class Links < Moonbase::Internal::Type::BaseModel
          attr_accessor self_: String

          attr_reader message: String?

          def message=: (String) -> String

          def initialize: (self_: String, ?message: String) -> void

          def to_hash: -> { self_: String, message: String }
        end
      end

      type activity_item_created =
        {
          id: String,
          links: Moonbase::Activity::ActivityItemCreated::Links,
          occurred_at: Time,
          type: :"activity/item_created",
          collection: Moonbase::Collection,
          item: Moonbase::Item
        }

      class ActivityItemCreated < Moonbase::Internal::Type::BaseModel
        attr_accessor id: String

        attr_accessor links: Moonbase::Activity::ActivityItemCreated::Links

        attr_accessor occurred_at: Time

        attr_accessor type: :"activity/item_created"

        attr_reader collection: Moonbase::Collection?

        def collection=: (Moonbase::Collection) -> Moonbase::Collection

        attr_reader item: Moonbase::Item?

        def item=: (Moonbase::Item) -> Moonbase::Item

        def initialize: (
          id: String,
          links: Moonbase::Activity::ActivityItemCreated::Links,
          occurred_at: Time,
          ?collection: Moonbase::Collection,
          ?item: Moonbase::Item,
          ?type: :"activity/item_created"
        ) -> void

        def to_hash: -> {
          id: String,
          links: Moonbase::Activity::ActivityItemCreated::Links,
          occurred_at: Time,
          type: :"activity/item_created",
          collection: Moonbase::Collection,
          item: Moonbase::Item
        }

        type links = { self_: String, collection: String, item: String }

        class Links < Moonbase::Internal::Type::BaseModel
          attr_accessor self_: String

          attr_reader collection: String?

          def collection=: (String) -> String

          attr_reader item: String?

          def item=: (String) -> String

          def initialize: (
            self_: String,
            ?collection: String,
            ?item: String
          ) -> void

          def to_hash: -> { self_: String, collection: String, item: String }
        end
      end

      type activity_item_mentioned =
        {
          id: String,
          links: Moonbase::Activity::ActivityItemMentioned::Links,
          occurred_at: Time,
          type: :"activity/item_mentioned",
          collection: Moonbase::Collection,
          item: Moonbase::Item
        }

      class ActivityItemMentioned < Moonbase::Internal::Type::BaseModel
        attr_accessor id: String

        attr_accessor links: Moonbase::Activity::ActivityItemMentioned::Links

        attr_accessor occurred_at: Time

        attr_accessor type: :"activity/item_mentioned"

        attr_reader collection: Moonbase::Collection?

        def collection=: (Moonbase::Collection) -> Moonbase::Collection

        attr_reader item: Moonbase::Item?

        def item=: (Moonbase::Item) -> Moonbase::Item

        def initialize: (
          id: String,
          links: Moonbase::Activity::ActivityItemMentioned::Links,
          occurred_at: Time,
          ?collection: Moonbase::Collection,
          ?item: Moonbase::Item,
          ?type: :"activity/item_mentioned"
        ) -> void

        def to_hash: -> {
          id: String,
          links: Moonbase::Activity::ActivityItemMentioned::Links,
          occurred_at: Time,
          type: :"activity/item_mentioned",
          collection: Moonbase::Collection,
          item: Moonbase::Item
        }

        type links = { self_: String, collection: String, item: String }

        class Links < Moonbase::Internal::Type::BaseModel
          attr_accessor self_: String

          attr_reader collection: String?

          def collection=: (String) -> String

          attr_reader item: String?

          def item=: (String) -> String

          def initialize: (
            self_: String,
            ?collection: String,
            ?item: String
          ) -> void

          def to_hash: -> { self_: String, collection: String, item: String }
        end
      end

      type activity_meeting_held =
        {
          id: String,
          links: Moonbase::Activity::ActivityMeetingHeld::Links,
          occurred_at: Time,
          type: :"activity/meeting_held",
          attendees: ::Array[Moonbase::Attendee],
          meeting: Moonbase::Meeting
        }

      class ActivityMeetingHeld < Moonbase::Internal::Type::BaseModel
        attr_accessor id: String

        attr_accessor links: Moonbase::Activity::ActivityMeetingHeld::Links

        attr_accessor occurred_at: Time

        attr_accessor type: :"activity/meeting_held"

        attr_reader attendees: ::Array[Moonbase::Attendee]?

        def attendees=: (
          ::Array[Moonbase::Attendee]
        ) -> ::Array[Moonbase::Attendee]

        attr_reader meeting: Moonbase::Meeting?

        def meeting=: (Moonbase::Meeting) -> Moonbase::Meeting

        def initialize: (
          id: String,
          links: Moonbase::Activity::ActivityMeetingHeld::Links,
          occurred_at: Time,
          ?attendees: ::Array[Moonbase::Attendee],
          ?meeting: Moonbase::Meeting,
          ?type: :"activity/meeting_held"
        ) -> void

        def to_hash: -> {
          id: String,
          links: Moonbase::Activity::ActivityMeetingHeld::Links,
          occurred_at: Time,
          type: :"activity/meeting_held",
          attendees: ::Array[Moonbase::Attendee],
          meeting: Moonbase::Meeting
        }

        type links = { self_: String, meeting: String }

        class Links < Moonbase::Internal::Type::BaseModel
          attr_accessor self_: String

          attr_reader meeting: String?

          def meeting=: (String) -> String

          def initialize: (self_: String, ?meeting: String) -> void

          def to_hash: -> { self_: String, meeting: String }
        end
      end

      type activity_meeting_scheduled =
        {
          id: String,
          links: Moonbase::Activity::ActivityMeetingScheduled::Links,
          occurred_at: Time,
          type: :"activity/meeting_scheduled",
          attendees: ::Array[Moonbase::Attendee],
          meeting: Moonbase::Meeting,
          organizer: Moonbase::Organizer
        }

      class ActivityMeetingScheduled < Moonbase::Internal::Type::BaseModel
        attr_accessor id: String

        attr_accessor links: Moonbase::Activity::ActivityMeetingScheduled::Links

        attr_accessor occurred_at: Time

        attr_accessor type: :"activity/meeting_scheduled"

        attr_reader attendees: ::Array[Moonbase::Attendee]?

        def attendees=: (
          ::Array[Moonbase::Attendee]
        ) -> ::Array[Moonbase::Attendee]

        attr_reader meeting: Moonbase::Meeting?

        def meeting=: (Moonbase::Meeting) -> Moonbase::Meeting

        attr_reader organizer: Moonbase::Organizer?

        def organizer=: (Moonbase::Organizer) -> Moonbase::Organizer

        def initialize: (
          id: String,
          links: Moonbase::Activity::ActivityMeetingScheduled::Links,
          occurred_at: Time,
          ?attendees: ::Array[Moonbase::Attendee],
          ?meeting: Moonbase::Meeting,
          ?organizer: Moonbase::Organizer,
          ?type: :"activity/meeting_scheduled"
        ) -> void

        def to_hash: -> {
          id: String,
          links: Moonbase::Activity::ActivityMeetingScheduled::Links,
          occurred_at: Time,
          type: :"activity/meeting_scheduled",
          attendees: ::Array[Moonbase::Attendee],
          meeting: Moonbase::Meeting,
          organizer: Moonbase::Organizer
        }

        type links = { self_: String, meeting: String }

        class Links < Moonbase::Internal::Type::BaseModel
          attr_accessor self_: String

          attr_reader meeting: String?

          def meeting=: (String) -> String

          def initialize: (self_: String, ?meeting: String) -> void

          def to_hash: -> { self_: String, meeting: String }
        end
      end

      type activity_note_created =
        {
          id: String,
          links: Moonbase::Activity::ActivityNoteCreated::Links,
          occurred_at: Time,
          type: :"activity/note_created",
          note: Moonbase::Note,
          related_item: Moonbase::Item,
          related_meeting: Moonbase::Meeting
        }

      class ActivityNoteCreated < Moonbase::Internal::Type::BaseModel
        attr_accessor id: String

        attr_accessor links: Moonbase::Activity::ActivityNoteCreated::Links

        attr_accessor occurred_at: Time

        attr_accessor type: :"activity/note_created"

        attr_reader note: Moonbase::Note?

        def note=: (Moonbase::Note) -> Moonbase::Note

        attr_reader related_item: Moonbase::Item?

        def related_item=: (Moonbase::Item) -> Moonbase::Item

        attr_reader related_meeting: Moonbase::Meeting?

        def related_meeting=: (Moonbase::Meeting) -> Moonbase::Meeting

        def initialize: (
          id: String,
          links: Moonbase::Activity::ActivityNoteCreated::Links,
          occurred_at: Time,
          ?note: Moonbase::Note,
          ?related_item: Moonbase::Item,
          ?related_meeting: Moonbase::Meeting,
          ?type: :"activity/note_created"
        ) -> void

        def to_hash: -> {
          id: String,
          links: Moonbase::Activity::ActivityNoteCreated::Links,
          occurred_at: Time,
          type: :"activity/note_created",
          note: Moonbase::Note,
          related_item: Moonbase::Item,
          related_meeting: Moonbase::Meeting
        }

        type links =
          {
            self_: String,
            note: String,
            related_item: String,
            related_meeting: String
          }

        class Links < Moonbase::Internal::Type::BaseModel
          attr_accessor self_: String

          attr_reader note: String?

          def note=: (String) -> String

          attr_reader related_item: String?

          def related_item=: (String) -> String

          attr_reader related_meeting: String?

          def related_meeting=: (String) -> String

          def initialize: (
            self_: String,
            ?note: String,
            ?related_item: String,
            ?related_meeting: String
          ) -> void

          def to_hash: -> {
            self_: String,
            note: String,
            related_item: String,
            related_meeting: String
          }
        end
      end

      type activity_program_message_bounced =
        {
          id: String,
          links: Moonbase::Activity::ActivityProgramMessageBounced::Links,
          occurred_at: Time,
          type: :"activity/program_message_bounced",
          recipient: Moonbase::Address
        }

      class ActivityProgramMessageBounced < Moonbase::Internal::Type::BaseModel
        attr_accessor id: String

        attr_accessor links: Moonbase::Activity::ActivityProgramMessageBounced::Links

        attr_accessor occurred_at: Time

        attr_accessor type: :"activity/program_message_bounced"

        attr_reader recipient: Moonbase::Address?

        def recipient=: (Moonbase::Address) -> Moonbase::Address

        def initialize: (
          id: String,
          links: Moonbase::Activity::ActivityProgramMessageBounced::Links,
          occurred_at: Time,
          ?recipient: Moonbase::Address,
          ?type: :"activity/program_message_bounced"
        ) -> void

        def to_hash: -> {
          id: String,
          links: Moonbase::Activity::ActivityProgramMessageBounced::Links,
          occurred_at: Time,
          type: :"activity/program_message_bounced",
          recipient: Moonbase::Address
        }

        type links = { self_: String }

        class Links < Moonbase::Internal::Type::BaseModel
          attr_accessor self_: String

          def initialize: (self_: String) -> void

          def to_hash: -> { self_: String }
        end
      end

      type activity_program_message_clicked =
        {
          id: String,
          links: Moonbase::Activity::ActivityProgramMessageClicked::Links,
          occurred_at: Time,
          type: :"activity/program_message_clicked",
          link_text: String,
          link_url_unsafe: String,
          recipient: Moonbase::Address
        }

      class ActivityProgramMessageClicked < Moonbase::Internal::Type::BaseModel
        attr_accessor id: String

        attr_accessor links: Moonbase::Activity::ActivityProgramMessageClicked::Links

        attr_accessor occurred_at: Time

        attr_accessor type: :"activity/program_message_clicked"

        attr_reader link_text: String?

        def link_text=: (String) -> String

        attr_reader link_url_unsafe: String?

        def link_url_unsafe=: (String) -> String

        attr_reader recipient: Moonbase::Address?

        def recipient=: (Moonbase::Address) -> Moonbase::Address

        def initialize: (
          id: String,
          links: Moonbase::Activity::ActivityProgramMessageClicked::Links,
          occurred_at: Time,
          ?link_text: String,
          ?link_url_unsafe: String,
          ?recipient: Moonbase::Address,
          ?type: :"activity/program_message_clicked"
        ) -> void

        def to_hash: -> {
          id: String,
          links: Moonbase::Activity::ActivityProgramMessageClicked::Links,
          occurred_at: Time,
          type: :"activity/program_message_clicked",
          link_text: String,
          link_url_unsafe: String,
          recipient: Moonbase::Address
        }

        type links = { self_: String }

        class Links < Moonbase::Internal::Type::BaseModel
          attr_accessor self_: String

          def initialize: (self_: String) -> void

          def to_hash: -> { self_: String }
        end
      end

      type activity_program_message_complained =
        {
          id: String,
          links: Moonbase::Activity::ActivityProgramMessageComplained::Links,
          occurred_at: Time,
          type: :"activity/program_message_complained",
          recipient: Moonbase::Address
        }

      class ActivityProgramMessageComplained < Moonbase::Internal::Type::BaseModel
        attr_accessor id: String

        attr_accessor links: Moonbase::Activity::ActivityProgramMessageComplained::Links

        attr_accessor occurred_at: Time

        attr_accessor type: :"activity/program_message_complained"

        attr_reader recipient: Moonbase::Address?

        def recipient=: (Moonbase::Address) -> Moonbase::Address

        def initialize: (
          id: String,
          links: Moonbase::Activity::ActivityProgramMessageComplained::Links,
          occurred_at: Time,
          ?recipient: Moonbase::Address,
          ?type: :"activity/program_message_complained"
        ) -> void

        def to_hash: -> {
          id: String,
          links: Moonbase::Activity::ActivityProgramMessageComplained::Links,
          occurred_at: Time,
          type: :"activity/program_message_complained",
          recipient: Moonbase::Address
        }

        type links = { self_: String }

        class Links < Moonbase::Internal::Type::BaseModel
          attr_accessor self_: String

          def initialize: (self_: String) -> void

          def to_hash: -> { self_: String }
        end
      end

      type activity_program_message_failed =
        {
          id: String,
          links: Moonbase::Activity::ActivityProgramMessageFailed::Links,
          occurred_at: Time,
          type: :"activity/program_message_failed",
          recipient: Moonbase::Address
        }

      class ActivityProgramMessageFailed < Moonbase::Internal::Type::BaseModel
        attr_accessor id: String

        attr_accessor links: Moonbase::Activity::ActivityProgramMessageFailed::Links

        attr_accessor occurred_at: Time

        attr_accessor type: :"activity/program_message_failed"

        attr_reader recipient: Moonbase::Address?

        def recipient=: (Moonbase::Address) -> Moonbase::Address

        def initialize: (
          id: String,
          links: Moonbase::Activity::ActivityProgramMessageFailed::Links,
          occurred_at: Time,
          ?recipient: Moonbase::Address,
          ?type: :"activity/program_message_failed"
        ) -> void

        def to_hash: -> {
          id: String,
          links: Moonbase::Activity::ActivityProgramMessageFailed::Links,
          occurred_at: Time,
          type: :"activity/program_message_failed",
          recipient: Moonbase::Address
        }

        type links = { self_: String }

        class Links < Moonbase::Internal::Type::BaseModel
          attr_accessor self_: String

          def initialize: (self_: String) -> void

          def to_hash: -> { self_: String }
        end
      end

      type activity_program_message_opened =
        {
          id: String,
          links: Moonbase::Activity::ActivityProgramMessageOpened::Links,
          occurred_at: Time,
          type: :"activity/program_message_opened",
          recipient: Moonbase::Address
        }

      class ActivityProgramMessageOpened < Moonbase::Internal::Type::BaseModel
        attr_accessor id: String

        attr_accessor links: Moonbase::Activity::ActivityProgramMessageOpened::Links

        attr_accessor occurred_at: Time

        attr_accessor type: :"activity/program_message_opened"

        attr_reader recipient: Moonbase::Address?

        def recipient=: (Moonbase::Address) -> Moonbase::Address

        def initialize: (
          id: String,
          links: Moonbase::Activity::ActivityProgramMessageOpened::Links,
          occurred_at: Time,
          ?recipient: Moonbase::Address,
          ?type: :"activity/program_message_opened"
        ) -> void

        def to_hash: -> {
          id: String,
          links: Moonbase::Activity::ActivityProgramMessageOpened::Links,
          occurred_at: Time,
          type: :"activity/program_message_opened",
          recipient: Moonbase::Address
        }

        type links = { self_: String }

        class Links < Moonbase::Internal::Type::BaseModel
          attr_accessor self_: String

          def initialize: (self_: String) -> void

          def to_hash: -> { self_: String }
        end
      end

      type activity_program_message_sent =
        {
          id: String,
          links: Moonbase::Activity::ActivityProgramMessageSent::Links,
          occurred_at: Time,
          type: :"activity/program_message_sent",
          recipient: Moonbase::Address
        }

      class ActivityProgramMessageSent < Moonbase::Internal::Type::BaseModel
        attr_accessor id: String

        attr_accessor links: Moonbase::Activity::ActivityProgramMessageSent::Links

        attr_accessor occurred_at: Time

        attr_accessor type: :"activity/program_message_sent"

        attr_reader recipient: Moonbase::Address?

        def recipient=: (Moonbase::Address) -> Moonbase::Address

        def initialize: (
          id: String,
          links: Moonbase::Activity::ActivityProgramMessageSent::Links,
          occurred_at: Time,
          ?recipient: Moonbase::Address,
          ?type: :"activity/program_message_sent"
        ) -> void

        def to_hash: -> {
          id: String,
          links: Moonbase::Activity::ActivityProgramMessageSent::Links,
          occurred_at: Time,
          type: :"activity/program_message_sent",
          recipient: Moonbase::Address
        }

        type links = { self_: String }

        class Links < Moonbase::Internal::Type::BaseModel
          attr_accessor self_: String

          def initialize: (self_: String) -> void

          def to_hash: -> { self_: String }
        end
      end

      type activity_program_message_shielded =
        {
          id: String,
          links: Moonbase::Activity::ActivityProgramMessageShielded::Links,
          occurred_at: Time,
          type: :"activity/program_message_shielded",
          recipient: Moonbase::Address
        }

      class ActivityProgramMessageShielded < Moonbase::Internal::Type::BaseModel
        attr_accessor id: String

        attr_accessor links: Moonbase::Activity::ActivityProgramMessageShielded::Links

        attr_accessor occurred_at: Time

        attr_accessor type: :"activity/program_message_shielded"

        attr_reader recipient: Moonbase::Address?

        def recipient=: (Moonbase::Address) -> Moonbase::Address

        def initialize: (
          id: String,
          links: Moonbase::Activity::ActivityProgramMessageShielded::Links,
          occurred_at: Time,
          ?recipient: Moonbase::Address,
          ?type: :"activity/program_message_shielded"
        ) -> void

        def to_hash: -> {
          id: String,
          links: Moonbase::Activity::ActivityProgramMessageShielded::Links,
          occurred_at: Time,
          type: :"activity/program_message_shielded",
          recipient: Moonbase::Address
        }

        type links = { self_: String }

        class Links < Moonbase::Internal::Type::BaseModel
          attr_accessor self_: String

          def initialize: (self_: String) -> void

          def to_hash: -> { self_: String }
        end
      end

      type activity_program_message_unsubscribed =
        {
          id: String,
          links: Moonbase::Activity::ActivityProgramMessageUnsubscribed::Links,
          occurred_at: Time,
          type: :"activity/program_message_unsubscribed",
          recipient: Moonbase::Address
        }

      class ActivityProgramMessageUnsubscribed < Moonbase::Internal::Type::BaseModel
        attr_accessor id: String

        attr_accessor links: Moonbase::Activity::ActivityProgramMessageUnsubscribed::Links

        attr_accessor occurred_at: Time

        attr_accessor type: :"activity/program_message_unsubscribed"

        attr_reader recipient: Moonbase::Address?

        def recipient=: (Moonbase::Address) -> Moonbase::Address

        def initialize: (
          id: String,
          links: Moonbase::Activity::ActivityProgramMessageUnsubscribed::Links,
          occurred_at: Time,
          ?recipient: Moonbase::Address,
          ?type: :"activity/program_message_unsubscribed"
        ) -> void

        def to_hash: -> {
          id: String,
          links: Moonbase::Activity::ActivityProgramMessageUnsubscribed::Links,
          occurred_at: Time,
          type: :"activity/program_message_unsubscribed",
          recipient: Moonbase::Address
        }

        type links = { self_: String }

        class Links < Moonbase::Internal::Type::BaseModel
          attr_accessor self_: String

          def initialize: (self_: String) -> void

          def to_hash: -> { self_: String }
        end
      end

      def self?.variants: -> ::Array[Moonbase::Models::activity]
    end
  end
end
