module Moonbase
  module Models
    type activity_program_message_shielded =
      {
        id: String,
        occurred_at: Time,
        program_message: Moonbase::Pointer?,
        recipient: Moonbase::ItemPointer?,
        type: :"activity/program_message_shielded",
        reason_code: Moonbase::Models::ActivityProgramMessageShielded::reason_code
      }

    class ActivityProgramMessageShielded < Moonbase::Internal::Type::BaseModel
      attr_accessor id: String

      attr_accessor occurred_at: Time

      attr_accessor program_message: Moonbase::Pointer?

      attr_accessor recipient: Moonbase::ItemPointer?

      attr_accessor type: :"activity/program_message_shielded"

      attr_reader reason_code: Moonbase::Models::ActivityProgramMessageShielded::reason_code?

      def reason_code=: (
        Moonbase::Models::ActivityProgramMessageShielded::reason_code
      ) -> Moonbase::Models::ActivityProgramMessageShielded::reason_code

      def initialize: (
        id: String,
        occurred_at: Time,
        program_message: Moonbase::Pointer?,
        recipient: Moonbase::ItemPointer?,
        ?reason_code: Moonbase::Models::ActivityProgramMessageShielded::reason_code,
        ?type: :"activity/program_message_shielded"
      ) -> void

      def to_hash: -> {
        id: String,
        occurred_at: Time,
        program_message: Moonbase::Pointer?,
        recipient: Moonbase::ItemPointer?,
        type: :"activity/program_message_shielded",
        reason_code: Moonbase::Models::ActivityProgramMessageShielded::reason_code
      }

      type reason_code =
        :person_previously_unsubscribed | :email_on_unsubscribe_list

      module ReasonCode
        extend Moonbase::Internal::Type::Enum

        PERSON_PREVIOUSLY_UNSUBSCRIBED: :person_previously_unsubscribed
        EMAIL_ON_UNSUBSCRIBE_LIST: :email_on_unsubscribe_list

        def self?.values: -> ::Array[Moonbase::Models::ActivityProgramMessageShielded::reason_code]
      end
    end
  end
end
