module Moonbase
  module Models
    type activity_note_created =
      {
        id: String,
        note: Moonbase::Pointer?,
        occurred_at: Time,
        related_item: Moonbase::ItemPointer?,
        related_meeting: Moonbase::Pointer?,
        type: :"activity/note_created"
      }

    class ActivityNoteCreated < Moonbase::Internal::Type::BaseModel
      attr_accessor id: String

      attr_accessor note: Moonbase::Pointer?

      attr_accessor occurred_at: Time

      attr_accessor related_item: Moonbase::ItemPointer?

      attr_accessor related_meeting: Moonbase::Pointer?

      attr_accessor type: :"activity/note_created"

      def initialize: (
        id: String,
        note: Moonbase::Pointer?,
        occurred_at: Time,
        related_item: Moonbase::ItemPointer?,
        related_meeting: Moonbase::Pointer?,
        ?type: :"activity/note_created"
      ) -> void

      def to_hash: -> {
        id: String,
        note: Moonbase::Pointer?,
        occurred_at: Time,
        related_item: Moonbase::ItemPointer?,
        related_meeting: Moonbase::Pointer?,
        type: :"activity/note_created"
      }
    end
  end
end
