module Moonbase
  module Models
    type activity_meeting_scheduled =
      {
        id: String,
        meeting: Moonbase::Pointer?,
        occurred_at: Time,
        type: :"activity/meeting_scheduled"
      }

    class ActivityMeetingScheduled < Moonbase::Internal::Type::BaseModel
      attr_accessor id: String

      attr_accessor meeting: Moonbase::Pointer?

      attr_accessor occurred_at: Time

      attr_accessor type: :"activity/meeting_scheduled"

      def initialize: (
        id: String,
        meeting: Moonbase::Pointer?,
        occurred_at: Time,
        ?type: :"activity/meeting_scheduled"
      ) -> void

      def to_hash: -> {
        id: String,
        meeting: Moonbase::Pointer?,
        occurred_at: Time,
        type: :"activity/meeting_scheduled"
      }
    end
  end
end
