module Moonbase
  module Models
    type activity =
      Moonbase::ActivityCallOccurred
      | Moonbase::ActivityFormSubmitted
      | Moonbase::ActivityInboxMessageSent
      | Moonbase::ActivityItemCreated
      | Moonbase::ActivityItemMentioned
      | Moonbase::ActivityItemMerged
      | Moonbase::ActivityMeetingHeld
      | Moonbase::ActivityMeetingScheduled
      | Moonbase::ActivityNoteCreated
      | Moonbase::ActivityProgramMessageBounced
      | Moonbase::ActivityProgramMessageClicked
      | Moonbase::ActivityProgramMessageComplained
      | Moonbase::ActivityProgramMessageFailed
      | Moonbase::ActivityProgramMessageOpened
      | Moonbase::ActivityProgramMessageSent
      | Moonbase::ActivityProgramMessageShielded
      | Moonbase::ActivityProgramMessageUnsubscribed

    module Activity
      extend Moonbase::Internal::Type::Union

      def self?.variants: -> ::Array[Moonbase::Models::activity]
    end
  end
end
