module Moonbase
  module Models
    type address =
      {
        id: String,
        email: String,
        role: Moonbase::Models::Address::role,
        type: :message_address,
        organization: Moonbase::Pointer,
        person: Moonbase::Pointer
      }

    class Address < Moonbase::Internal::Type::BaseModel
      attr_accessor id: String

      attr_accessor email: String

      attr_accessor role: Moonbase::Models::Address::role

      attr_accessor type: :message_address

      attr_reader organization: Moonbase::Pointer?

      def organization=: (Moonbase::Pointer) -> Moonbase::Pointer

      attr_reader person: Moonbase::Pointer?

      def person=: (Moonbase::Pointer) -> Moonbase::Pointer

      def initialize: (
        id: String,
        email: String,
        role: Moonbase::Models::Address::role,
        ?organization: Moonbase::Pointer,
        ?person: Moonbase::Pointer,
        ?type: :message_address
      ) -> void

      def to_hash: -> {
        id: String,
        email: String,
        role: Moonbase::Models::Address::role,
        type: :message_address,
        organization: Moonbase::Pointer,
        person: Moonbase::Pointer
      }

      type role = :from | :reply_to | :to | :cc | :bcc

      module Role
        extend Moonbase::Internal::Type::Enum

        FROM: :from
        REPLY_TO: :reply_to
        TO: :to
        CC: :cc
        BCC: :bcc

        def self?.values: -> ::Array[Moonbase::Models::Address::role]
      end
    end
  end
end
