module Moonbase
  module Models
    type attendee =
      {
        id: String,
        email: String,
        type: :meeting_attendee,
        organization: Moonbase::Pointer,
        person: Moonbase::Pointer
      }

    class Attendee < Moonbase::Internal::Type::BaseModel
      attr_accessor id: String

      attr_accessor email: String

      attr_accessor type: :meeting_attendee

      attr_reader organization: Moonbase::Pointer?

      def organization=: (Moonbase::Pointer) -> Moonbase::Pointer

      attr_reader person: Moonbase::Pointer?

      def person=: (Moonbase::Pointer) -> Moonbase::Pointer

      def initialize: (
        id: String,
        email: String,
        ?organization: Moonbase::Pointer,
        ?person: Moonbase::Pointer,
        ?type: :meeting_attendee
      ) -> void

      def to_hash: -> {
        id: String,
        email: String,
        type: :meeting_attendee,
        organization: Moonbase::Pointer,
        person: Moonbase::Pointer
      }
    end
  end
end
