module Moonbase
  module Models
    type boolean_value = { data: bool, type: :"value/boolean" }

    class BooleanValue < Moonbase::Internal::Type::BaseModel
      attr_accessor data: bool

      attr_accessor type: :"value/boolean"

      def initialize: (data: bool, ?type: :"value/boolean") -> void

      def to_hash: -> { data: bool, type: :"value/boolean" }
    end
  end
end
