module Moonbase
  module Models
    type call =
      {
        id: String,
        created_at: Time,
        direction: Moonbase::Models::Call::direction,
        participants: ::Array[Moonbase::Call::Participant],
        provider: String,
        provider_id: String,
        provider_status: String,
        start_at: Time,
        type: :call,
        updated_at: Time,
        answered_at: Time,
        end_at: Time,
        provider_metadata: ::Hash[Symbol, top]
      }

    class Call < Moonbase::Internal::Type::BaseModel
      attr_accessor id: String

      attr_accessor created_at: Time

      attr_accessor direction: Moonbase::Models::Call::direction

      attr_accessor participants: ::Array[Moonbase::Call::Participant]

      attr_accessor provider: String

      attr_accessor provider_id: String

      attr_accessor provider_status: String

      attr_accessor start_at: Time

      attr_accessor type: :call

      attr_accessor updated_at: Time

      attr_reader answered_at: Time?

      def answered_at=: (Time) -> Time

      attr_reader end_at: Time?

      def end_at=: (Time) -> Time

      attr_reader provider_metadata: ::Hash[Symbol, top]?

      def provider_metadata=: (::Hash[Symbol, top]) -> ::Hash[Symbol, top]

      def initialize: (
        id: String,
        created_at: Time,
        direction: Moonbase::Models::Call::direction,
        participants: ::Array[Moonbase::Call::Participant],
        provider: String,
        provider_id: String,
        provider_status: String,
        start_at: Time,
        updated_at: Time,
        ?answered_at: Time,
        ?end_at: Time,
        ?provider_metadata: ::Hash[Symbol, top],
        ?type: :call
      ) -> void

      def to_hash: -> {
        id: String,
        created_at: Time,
        direction: Moonbase::Models::Call::direction,
        participants: ::Array[Moonbase::Call::Participant],
        provider: String,
        provider_id: String,
        provider_status: String,
        start_at: Time,
        type: :call,
        updated_at: Time,
        answered_at: Time,
        end_at: Time,
        provider_metadata: ::Hash[Symbol, top]
      }

      type direction = :incoming | :outgoing

      module Direction
        extend Moonbase::Internal::Type::Enum

        INCOMING: :incoming
        OUTGOING: :outgoing

        def self?.values: -> ::Array[Moonbase::Models::Call::direction]
      end

      type participant =
        {
          id: String,
          phone: String,
          role: Moonbase::Models::Call::Participant::role,
          type: :call_participant,
          organization: Moonbase::Pointer,
          person: Moonbase::Pointer
        }

      class Participant < Moonbase::Internal::Type::BaseModel
        attr_accessor id: String

        attr_accessor phone: String

        attr_accessor role: Moonbase::Models::Call::Participant::role

        attr_accessor type: :call_participant

        attr_reader organization: Moonbase::Pointer?

        def organization=: (Moonbase::Pointer) -> Moonbase::Pointer

        attr_reader person: Moonbase::Pointer?

        def person=: (Moonbase::Pointer) -> Moonbase::Pointer

        def initialize: (
          id: String,
          phone: String,
          role: Moonbase::Models::Call::Participant::role,
          ?organization: Moonbase::Pointer,
          ?person: Moonbase::Pointer,
          ?type: :call_participant
        ) -> void

        def to_hash: -> {
          id: String,
          phone: String,
          role: Moonbase::Models::Call::Participant::role,
          type: :call_participant,
          organization: Moonbase::Pointer,
          person: Moonbase::Pointer
        }

        type role = :caller | :callee | :other

        module Role
          extend Moonbase::Internal::Type::Enum

          CALLER: :caller
          CALLEE: :callee
          OTHER: :other

          def self?.values: -> ::Array[Moonbase::Models::Call::Participant::role]
        end
      end
    end
  end
end
