module Moonbase
  module Models
    type call =
      {
        id: String,
        created_at: Time,
        direction: Moonbase::Models::Call::direction,
        participants: ::Array[Moonbase::CallParticipant],
        provider: Moonbase::Models::Call::provider,
        provider_id: String,
        provider_status: String,
        start_at: Time,
        tags: ::Array[Moonbase::Tag],
        type: :call,
        updated_at: Time,
        answered_at: Time,
        end_at: Time,
        note: Moonbase::Note?,
        provider_metadata: ::Hash[Symbol, top],
        summary: Moonbase::Note?,
        transcript: Moonbase::CallTranscript?
      }

    class Call < Moonbase::Internal::Type::BaseModel
      attr_accessor id: String

      attr_accessor created_at: Time

      attr_accessor direction: Moonbase::Models::Call::direction

      attr_accessor participants: ::Array[Moonbase::CallParticipant]

      attr_accessor provider: Moonbase::Models::Call::provider

      attr_accessor provider_id: String

      attr_accessor provider_status: String

      attr_accessor start_at: Time

      attr_accessor tags: ::Array[Moonbase::Tag]

      attr_accessor type: :call

      attr_accessor updated_at: Time

      attr_reader answered_at: Time?

      def answered_at=: (Time) -> Time

      attr_reader end_at: Time?

      def end_at=: (Time) -> Time

      attr_accessor note: Moonbase::Note?

      attr_reader provider_metadata: ::Hash[Symbol, top]?

      def provider_metadata=: (::Hash[Symbol, top]) -> ::Hash[Symbol, top]

      attr_accessor summary: Moonbase::Note?

      attr_accessor transcript: Moonbase::CallTranscript?

      def initialize: (
        id: String,
        created_at: Time,
        direction: Moonbase::Models::Call::direction,
        participants: ::Array[Moonbase::CallParticipant],
        provider: Moonbase::Models::Call::provider,
        provider_id: String,
        provider_status: String,
        start_at: Time,
        tags: ::Array[Moonbase::Tag],
        updated_at: Time,
        ?answered_at: Time,
        ?end_at: Time,
        ?note: Moonbase::Note?,
        ?provider_metadata: ::Hash[Symbol, top],
        ?summary: Moonbase::Note?,
        ?transcript: Moonbase::CallTranscript?,
        ?type: :call
      ) -> void

      def to_hash: -> {
        id: String,
        created_at: Time,
        direction: Moonbase::Models::Call::direction,
        participants: ::Array[Moonbase::CallParticipant],
        provider: Moonbase::Models::Call::provider,
        provider_id: String,
        provider_status: String,
        start_at: Time,
        tags: ::Array[Moonbase::Tag],
        type: :call,
        updated_at: Time,
        answered_at: Time,
        end_at: Time,
        note: Moonbase::Note?,
        provider_metadata: ::Hash[Symbol, top],
        summary: Moonbase::Note?,
        transcript: Moonbase::CallTranscript?
      }

      type direction = :incoming | :outgoing

      module Direction
        extend Moonbase::Internal::Type::Enum

        INCOMING: :incoming
        OUTGOING: :outgoing

        def self?.values: -> ::Array[Moonbase::Models::Call::direction]
      end

      type provider = :openphone | :user | :zoom_phone

      module Provider
        extend Moonbase::Internal::Type::Enum

        OPENPHONE: :openphone
        USER: :user
        ZOOM_PHONE: :zoom_phone

        def self?.values: -> ::Array[Moonbase::Models::Call::provider]
      end
    end
  end
end
