module Moonbase
  module Models
    type choice_field_option =
      {
        id: String,
        color: Moonbase::Models::ChoiceFieldOption::color,
        name: String,
        type: :choice_field_option
      }

    class ChoiceFieldOption < Moonbase::Internal::Type::BaseModel
      attr_accessor id: String

      attr_accessor color: Moonbase::Models::ChoiceFieldOption::color

      attr_accessor name: String

      attr_accessor type: :choice_field_option

      def initialize: (
        id: String,
        color: Moonbase::Models::ChoiceFieldOption::color,
        name: String,
        ?type: :choice_field_option
      ) -> void

      def to_hash: -> {
        id: String,
        color: Moonbase::Models::ChoiceFieldOption::color,
        name: String,
        type: :choice_field_option
      }

      type color =
        :amber
        | :blue
        | :cyan
        | :emerald
        | :fuchsia
        | :green
        | :indigo
        | :lime
        | :lunar
        | :orange
        | :pink
        | :purple
        | :red
        | :rose
        | :sky
        | :teal
        | :violet
        | :yellow

      module Color
        extend Moonbase::Internal::Type::Enum

        AMBER: :amber
        BLUE: :blue
        CYAN: :cyan
        EMERALD: :emerald
        FUCHSIA: :fuchsia
        GREEN: :green
        INDIGO: :indigo
        LIME: :lime
        LUNAR: :lunar
        ORANGE: :orange
        PINK: :pink
        PURPLE: :purple
        RED: :red
        ROSE: :rose
        SKY: :sky
        TEAL: :teal
        VIOLET: :violet
        YELLOW: :yellow

        def self?.values: -> ::Array[Moonbase::Models::ChoiceFieldOption::color]
      end
    end
  end
end
