module Moonbase
  module Models
    type collection =
      {
        id: String,
        created_at: Time,
        fields: ::Array[Moonbase::Models::field],
        kind: Moonbase::Models::Collection::kind,
        name: String,
        ref: String,
        type: :collection,
        updated_at: Time,
        description: String,
        icon_name: String,
        views: ::Array[Moonbase::Collection::View]
      }

    class Collection < Moonbase::Internal::Type::BaseModel
      attr_accessor id: String

      attr_accessor created_at: Time

      attr_accessor fields: ::Array[Moonbase::Models::field]

      attr_accessor kind: Moonbase::Models::Collection::kind

      attr_accessor name: String

      attr_accessor ref: String

      attr_accessor type: :collection

      attr_accessor updated_at: Time

      attr_reader description: String?

      def description=: (String) -> String

      attr_reader icon_name: String?

      def icon_name=: (String) -> String

      attr_reader views: ::Array[Moonbase::Collection::View]?

      def views=: (
        ::Array[Moonbase::Collection::View]
      ) -> ::Array[Moonbase::Collection::View]

      def initialize: (
        id: String,
        created_at: Time,
        fields: ::Array[Moonbase::Models::field],
        kind: Moonbase::Models::Collection::kind,
        name: String,
        ref: String,
        updated_at: Time,
        ?description: String,
        ?icon_name: String,
        ?views: ::Array[Moonbase::Collection::View],
        ?type: :collection
      ) -> void

      def to_hash: -> {
        id: String,
        created_at: Time,
        fields: ::Array[Moonbase::Models::field],
        kind: Moonbase::Models::Collection::kind,
        name: String,
        ref: String,
        type: :collection,
        updated_at: Time,
        description: String,
        icon_name: String,
        views: ::Array[Moonbase::Collection::View]
      }

      type kind = :system | :form | :custom

      module Kind
        extend Moonbase::Internal::Type::Enum

        SYSTEM: :system
        FORM: :form
        CUSTOM: :custom

        def self?.values: -> ::Array[Moonbase::Models::Collection::kind]
      end

      type view =
        {
          id: String,
          collection: Moonbase::CollectionPointer,
          created_at: Time,
          name: String,
          type: :view,
          updated_at: Time,
          view_type: Moonbase::Models::Collection::View::view_type
        }

      class View < Moonbase::Internal::Type::BaseModel
        attr_accessor id: String

        attr_accessor collection: Moonbase::CollectionPointer

        attr_accessor created_at: Time

        attr_accessor name: String

        attr_accessor type: :view

        attr_accessor updated_at: Time

        attr_accessor view_type: Moonbase::Models::Collection::View::view_type

        def initialize: (
          id: String,
          collection: Moonbase::CollectionPointer,
          created_at: Time,
          name: String,
          updated_at: Time,
          view_type: Moonbase::Models::Collection::View::view_type,
          ?type: :view
        ) -> void

        def to_hash: -> {
          id: String,
          collection: Moonbase::CollectionPointer,
          created_at: Time,
          name: String,
          type: :view,
          updated_at: Time,
          view_type: Moonbase::Models::Collection::View::view_type
        }

        type view_type = :table | :board

        module ViewType
          extend Moonbase::Internal::Type::Enum

          TABLE: :table
          BOARD: :board

          def self?.values: -> ::Array[Moonbase::Models::Collection::View::view_type]
        end
      end
    end
  end
end
