module Moonbase
  module Models
    type collection_retrieve_params =
      { include: ::Array[Moonbase::Models::CollectionRetrieveParams::include_] }
      & Moonbase::Internal::Type::request_parameters

    class CollectionRetrieveParams < Moonbase::Internal::Type::BaseModel
      extend Moonbase::Internal::Type::RequestParameters::Converter
      include Moonbase::Internal::Type::RequestParameters

      attr_reader include: ::Array[Moonbase::Models::CollectionRetrieveParams::include_]?

      def include=: (
        ::Array[Moonbase::Models::CollectionRetrieveParams::include_]
      ) -> ::Array[Moonbase::Models::CollectionRetrieveParams::include_]

      def initialize: (
        ?include: ::Array[Moonbase::Models::CollectionRetrieveParams::include_],
        ?request_options: Moonbase::request_opts
      ) -> void

      def to_hash: -> {
        include: ::Array[Moonbase::Models::CollectionRetrieveParams::include_],
        request_options: Moonbase::RequestOptions
      }

      type include_ = :fields | :views

      module Include
        extend Moonbase::Internal::Type::Enum

        FIELDS: :fields
        VIEWS: :views

        def self?.values: -> ::Array[Moonbase::Models::CollectionRetrieveParams::include_]
      end
    end
  end
end
