module Moonbase
  module Models
    type collection =
      {
        id: String,
        core: bool,
        created_at: Time,
        fields: ::Array[Moonbase::Models::field],
        name: String,
        ref: String,
        type: :collection,
        updated_at: Time,
        description: String,
        views: ::Array[Moonbase::View]
      }

    class Collection < Moonbase::Internal::Type::BaseModel
      attr_accessor id: String

      attr_accessor core: bool

      attr_accessor created_at: Time

      attr_accessor fields: ::Array[Moonbase::Models::field]

      attr_accessor name: String

      attr_accessor ref: String

      attr_accessor type: :collection

      attr_accessor updated_at: Time

      attr_reader description: String?

      def description=: (String) -> String

      attr_reader views: ::Array[Moonbase::View]?

      def views=: (::Array[Moonbase::View]) -> ::Array[Moonbase::View]

      def initialize: (
        id: String,
        core: bool,
        created_at: Time,
        fields: ::Array[Moonbase::Models::field],
        name: String,
        ref: String,
        updated_at: Time,
        ?description: String,
        ?views: ::Array[Moonbase::View],
        ?type: :collection
      ) -> void

      def to_hash: -> {
        id: String,
        core: bool,
        created_at: Time,
        fields: ::Array[Moonbase::Models::field],
        name: String,
        ref: String,
        type: :collection,
        updated_at: Time,
        description: String,
        views: ::Array[Moonbase::View]
      }
    end
  end
end
