module Moonbase
  module Models
    type datetime_value = { data: Time, type: :"value/datetime" }

    class DatetimeValue < Moonbase::Internal::Type::BaseModel
      attr_accessor data: Time

      attr_accessor type: :"value/datetime"

      def initialize: (data: Time, ?type: :"value/datetime") -> void

      def to_hash: -> { data: Time, type: :"value/datetime" }
    end
  end
end
