module Moonbase
  module Models
    type date_value = { date: Date, type: :"value/date" }

    class DateValue < Moonbase::Internal::Type::BaseModel
      attr_accessor date: Date

      attr_accessor type: :"value/date"

      def initialize: (date: Date, ?type: :"value/date") -> void

      def to_hash: -> { date: Date, type: :"value/date" }
    end
  end
end
