module Moonbase
  module Models
    type date_value = { data: Date, type: :"value/date" }

    class DateValue < Moonbase::Internal::Type::BaseModel
      attr_accessor data: Date

      attr_accessor type: :"value/date"

      def initialize: (data: Date, ?type: :"value/date") -> void

      def to_hash: -> { data: Date, type: :"value/date" }
    end
  end
end
