module Moonbase
  module Models
    type domain_value = { data: String, type: :"value/uri/domain" }

    class DomainValue < Moonbase::Internal::Type::BaseModel
      attr_accessor data: String

      attr_accessor type: :"value/uri/domain"

      def initialize: (data: String, ?type: :"value/uri/domain") -> void

      def to_hash: -> { data: String, type: :"value/uri/domain" }
    end
  end
end
