module Moonbase
  module Models
    type email_value = { data: String, type: :"value/email" }

    class EmailValue < Moonbase::Internal::Type::BaseModel
      attr_accessor data: String

      attr_accessor type: :"value/email"

      def initialize: (data: String, ?type: :"value/email") -> void

      def to_hash: -> { data: String, type: :"value/email" }
    end
  end
end
