module Moonbase
  module Models
    type email_message =
      {
        id: String,
        body: Moonbase::FormattedText,
        bulk: bool,
        created_at: Time,
        draft: bool,
        spam: bool,
        subject: String,
        trash: bool,
        type: :email_message,
        unread: bool,
        addresses: ::Array[Moonbase::Address],
        attachments: ::Array[Moonbase::EmailMessage::Attachment],
        conversation: Moonbase::InboxConversation,
        summary: String
      }

    class EmailMessage < Moonbase::Internal::Type::BaseModel
      attr_accessor id: String

      attr_accessor body: Moonbase::FormattedText

      attr_accessor bulk: bool

      attr_accessor created_at: Time

      attr_accessor draft: bool

      attr_accessor spam: bool

      attr_accessor subject: String

      attr_accessor trash: bool

      attr_accessor type: :email_message

      attr_accessor unread: bool

      attr_reader addresses: ::Array[Moonbase::Address]?

      def addresses=: (::Array[Moonbase::Address]) -> ::Array[Moonbase::Address]

      attr_reader attachments: ::Array[Moonbase::EmailMessage::Attachment]?

      def attachments=: (
        ::Array[Moonbase::EmailMessage::Attachment]
      ) -> ::Array[Moonbase::EmailMessage::Attachment]

      attr_reader conversation: Moonbase::InboxConversation?

      def conversation=: (
        Moonbase::InboxConversation
      ) -> Moonbase::InboxConversation

      attr_reader summary: String?

      def summary=: (String) -> String

      def initialize: (
        id: String,
        body: Moonbase::FormattedText,
        bulk: bool,
        created_at: Time,
        draft: bool,
        spam: bool,
        subject: String,
        trash: bool,
        unread: bool,
        ?addresses: ::Array[Moonbase::Address],
        ?attachments: ::Array[Moonbase::EmailMessage::Attachment],
        ?conversation: Moonbase::InboxConversation,
        ?summary: String,
        ?type: :email_message
      ) -> void

      def to_hash: -> {
        id: String,
        body: Moonbase::FormattedText,
        bulk: bool,
        created_at: Time,
        draft: bool,
        spam: bool,
        subject: String,
        trash: bool,
        type: :email_message,
        unread: bool,
        addresses: ::Array[Moonbase::Address],
        attachments: ::Array[Moonbase::EmailMessage::Attachment],
        conversation: Moonbase::InboxConversation,
        summary: String
      }

      type attachment =
        {
          id: String,
          created_at: Time,
          download_url: String,
          filename: String,
          size: Integer,
          type: :message_attachment
        }

      class Attachment < Moonbase::Internal::Type::BaseModel
        attr_accessor id: String

        attr_accessor created_at: Time

        attr_accessor download_url: String

        attr_accessor filename: String

        attr_accessor size: Integer

        attr_accessor type: :message_attachment

        def initialize: (
          id: String,
          created_at: Time,
          download_url: String,
          filename: String,
          size: Integer,
          ?type: :message_attachment
        ) -> void

        def to_hash: -> {
          id: String,
          created_at: Time,
          download_url: String,
          filename: String,
          size: Integer,
          type: :message_attachment
        }
      end
    end
  end
end
