module Moonbase
  module Models
    type field =
      Moonbase::SingleLineTextField
      | Moonbase::MultiLineTextField
      | Moonbase::IntegerField
      | Moonbase::FloatField
      | Moonbase::MonetaryField
      | Moonbase::PercentageField
      | Moonbase::BooleanField
      | Moonbase::EmailField
      | Moonbase::URLField
      | Moonbase::DomainField
      | Moonbase::SocialXField
      | Moonbase::SocialLinkedInField
      | Moonbase::TelephoneNumberField
      | Moonbase::GeoField
      | Moonbase::DateField
      | Moonbase::DatetimeField
      | Moonbase::ChoiceField
      | Moonbase::StageField
      | Moonbase::RelationField

    module Field
      extend Moonbase::Internal::Type::Union

      def self?.variants: -> ::Array[Moonbase::Models::field]
    end
  end
end
