module Moonbase
  module Models
    type field_value_param =
      Moonbase::SingleLineTextValue
      | Moonbase::MultiLineTextValue
      | Moonbase::IntegerValue
      | Moonbase::FloatValue
      | Moonbase::MonetaryValue
      | Moonbase::PercentageValue
      | Moonbase::BooleanValue
      | Moonbase::EmailValue
      | Moonbase::URLValue
      | Moonbase::DomainValue
      | Moonbase::SocialXValueParam
      | Moonbase::SocialLinkedInValueParam
      | Moonbase::TelephoneNumber
      | Moonbase::GeoValue
      | Moonbase::DateValue
      | Moonbase::DatetimeValue
      | Moonbase::ChoiceValueParam
      | Moonbase::FunnelStepValueParam
      | Moonbase::RelationValueParam
      | ::Array[Moonbase::Models::value_param]

    module FieldValueParam
      extend Moonbase::Internal::Type::Union

      def self?.variants: -> ::Array[Moonbase::Models::field_value_param]

      ValueParamArray: Moonbase::Internal::Type::Converter
    end
  end
end
