module Moonbase
  module Models
    type float_value = { data: Float, type: :"value/number/unitless_float" }

    class FloatValue < Moonbase::Internal::Type::BaseModel
      attr_accessor data: Float

      attr_accessor type: :"value/number/unitless_float"

      def initialize: (
        data: Float,
        ?type: :"value/number/unitless_float"
      ) -> void

      def to_hash: -> { data: Float, type: :"value/number/unitless_float" }
    end
  end
end
