module Moonbase
  module Models
    type funnel_update_params =
      {
        id: String,
        name: String,
        steps: ::Array[Moonbase::FunnelUpdateParams::Step]
      }
      & Moonbase::Internal::Type::request_parameters

    class FunnelUpdateParams < Moonbase::Internal::Type::BaseModel
      extend Moonbase::Internal::Type::RequestParameters::Converter
      include Moonbase::Internal::Type::RequestParameters

      attr_accessor id: String

      attr_reader name: String?

      def name=: (String) -> String

      attr_reader steps: ::Array[Moonbase::FunnelUpdateParams::Step]?

      def steps=: (
        ::Array[Moonbase::FunnelUpdateParams::Step]
      ) -> ::Array[Moonbase::FunnelUpdateParams::Step]

      def initialize: (
        id: String,
        ?name: String,
        ?steps: ::Array[Moonbase::FunnelUpdateParams::Step],
        ?request_options: Moonbase::request_opts
      ) -> void

      def to_hash: -> {
        id: String,
        name: String,
        steps: ::Array[Moonbase::FunnelUpdateParams::Step],
        request_options: Moonbase::RequestOptions
      }

      type step =
        {
          color: Moonbase::Models::FunnelUpdateParams::Step::color,
          name: String,
          step_type: Moonbase::Models::FunnelUpdateParams::Step::step_type,
          id: String
        }

      class Step < Moonbase::Internal::Type::BaseModel
        attr_accessor color: Moonbase::Models::FunnelUpdateParams::Step::color

        attr_accessor name: String

        attr_accessor step_type: Moonbase::Models::FunnelUpdateParams::Step::step_type

        attr_reader id: String?

        def id=: (String) -> String

        def initialize: (
          color: Moonbase::Models::FunnelUpdateParams::Step::color,
          name: String,
          step_type: Moonbase::Models::FunnelUpdateParams::Step::step_type,
          ?id: String
        ) -> void

        def to_hash: -> {
          color: Moonbase::Models::FunnelUpdateParams::Step::color,
          name: String,
          step_type: Moonbase::Models::FunnelUpdateParams::Step::step_type,
          id: String
        }

        type color =
          :amber
          | :blue
          | :cyan
          | :emerald
          | :fuchsia
          | :green
          | :indigo
          | :lime
          | :lunar
          | :orange
          | :pink
          | :purple
          | :red
          | :rose
          | :sky
          | :teal
          | :violet
          | :yellow

        module Color
          extend Moonbase::Internal::Type::Enum

          AMBER: :amber
          BLUE: :blue
          CYAN: :cyan
          EMERALD: :emerald
          FUCHSIA: :fuchsia
          GREEN: :green
          INDIGO: :indigo
          LIME: :lime
          LUNAR: :lunar
          ORANGE: :orange
          PINK: :pink
          PURPLE: :purple
          RED: :red
          ROSE: :rose
          SKY: :sky
          TEAL: :teal
          VIOLET: :violet
          YELLOW: :yellow

          def self?.values: -> ::Array[Moonbase::Models::FunnelUpdateParams::Step::color]
        end

        type step_type = :active | :success | :failure

        module StepType
          extend Moonbase::Internal::Type::Enum

          ACTIVE: :active
          SUCCESS: :success
          FAILURE: :failure

          def self?.values: -> ::Array[Moonbase::Models::FunnelUpdateParams::Step::step_type]
        end
      end
    end
  end
end
