module Moonbase
  module Models
    type funnel_step_value_param =
      { data: Moonbase::FunnelStepPointer, type: :"value/funnel_step" }

    class FunnelStepValueParam < Moonbase::Internal::Type::BaseModel
      attr_accessor data: Moonbase::FunnelStepPointer

      attr_accessor type: :"value/funnel_step"

      def initialize: (
        data: Moonbase::FunnelStepPointer,
        ?type: :"value/funnel_step"
      ) -> void

      def to_hash: -> {
        data: Moonbase::FunnelStepPointer,
        type: :"value/funnel_step"
      }
    end
  end
end
