module Moonbase
  module Models
    type funnel_step =
      {
        id: String,
        name: String,
        step_type: Moonbase::Models::FunnelStep::step_type,
        type: :funnel_step
      }

    class FunnelStep < Moonbase::Internal::Type::BaseModel
      attr_accessor id: String

      attr_accessor name: String

      attr_accessor step_type: Moonbase::Models::FunnelStep::step_type

      attr_accessor type: :funnel_step

      def initialize: (
        id: String,
        name: String,
        step_type: Moonbase::Models::FunnelStep::step_type,
        ?type: :funnel_step
      ) -> void

      def to_hash: -> {
        id: String,
        name: String,
        step_type: Moonbase::Models::FunnelStep::step_type,
        type: :funnel_step
      }

      type step_type = :active | :success | :failure

      module StepType
        extend Moonbase::Internal::Type::Enum

        ACTIVE: :active
        SUCCESS: :success
        FAILURE: :failure

        def self?.values: -> ::Array[Moonbase::Models::FunnelStep::step_type]
      end
    end
  end
end
