module Moonbase
  module Models
    type geo_value = { geo: String, type: :"value/geo" }

    class GeoValue < Moonbase::Internal::Type::BaseModel
      attr_accessor geo: String

      attr_accessor type: :"value/geo"

      def initialize: (geo: String, ?type: :"value/geo") -> void

      def to_hash: -> { geo: String, type: :"value/geo" }
    end
  end
end
