module Moonbase
  module Models
    type geo_value = { data: String, type: :"value/geo" }

    class GeoValue < Moonbase::Internal::Type::BaseModel
      attr_accessor data: String

      attr_accessor type: :"value/geo"

      def initialize: (data: String, ?type: :"value/geo") -> void

      def to_hash: -> { data: String, type: :"value/geo" }
    end
  end
end
