module Moonbase
  module Models
    type inbox_message_create_params =
      { message: Moonbase::Models::InboxMessageCreateParams::message }
      & Moonbase::Internal::Type::request_parameters

    class InboxMessageCreateParams < Moonbase::Internal::Type::BaseModel
      extend Moonbase::Internal::Type::RequestParameters::Converter
      include Moonbase::Internal::Type::RequestParameters

      attr_accessor message: Moonbase::Models::InboxMessageCreateParams::message

      def initialize: (
        message: Moonbase::Models::InboxMessageCreateParams::message,
        ?request_options: Moonbase::request_opts
      ) -> void

      def to_hash: -> {
        message: Moonbase::Models::InboxMessageCreateParams::message,
        request_options: Moonbase::RequestOptions
      }

      type message =
        Moonbase::InboxMessageCreateParams::Message::EmailMessageNewConversationCreateParams
        | Moonbase::InboxMessageCreateParams::Message::SlackMessageNewConversationCreateParams
        | Moonbase::InboxMessageCreateParams::Message::EmailMessageReplyCreateParams
        | Moonbase::InboxMessageCreateParams::Message::SlackMessageReplyCreateParams

      module Message
        extend Moonbase::Internal::Type::Union

        type email_message_new_conversation_create_params =
          {
            body: Moonbase::FormattedText,
            inbox_id: String,
            subject: String,
            to: ::Array[Moonbase::EmailMessageAddressParams],
            type: :email_message,
            bcc: ::Array[Moonbase::EmailMessageAddressParams],
            cc: ::Array[Moonbase::EmailMessageAddressParams]
          }

        class EmailMessageNewConversationCreateParams < Moonbase::Internal::Type::BaseModel
          attr_accessor body: Moonbase::FormattedText

          attr_accessor inbox_id: String

          attr_accessor subject: String

          attr_accessor to: ::Array[Moonbase::EmailMessageAddressParams]

          attr_accessor type: :email_message

          attr_reader bcc: ::Array[Moonbase::EmailMessageAddressParams]?

          def bcc=: (
            ::Array[Moonbase::EmailMessageAddressParams]
          ) -> ::Array[Moonbase::EmailMessageAddressParams]

          attr_reader cc: ::Array[Moonbase::EmailMessageAddressParams]?

          def cc=: (
            ::Array[Moonbase::EmailMessageAddressParams]
          ) -> ::Array[Moonbase::EmailMessageAddressParams]

          def initialize: (
            body: Moonbase::FormattedText,
            inbox_id: String,
            subject: String,
            to: ::Array[Moonbase::EmailMessageAddressParams],
            ?bcc: ::Array[Moonbase::EmailMessageAddressParams],
            ?cc: ::Array[Moonbase::EmailMessageAddressParams],
            ?type: :email_message
          ) -> void

          def to_hash: -> {
            body: Moonbase::FormattedText,
            inbox_id: String,
            subject: String,
            to: ::Array[Moonbase::EmailMessageAddressParams],
            type: :email_message,
            bcc: ::Array[Moonbase::EmailMessageAddressParams],
            cc: ::Array[Moonbase::EmailMessageAddressParams]
          }
        end

        type slack_message_new_conversation_create_params =
          {
            body: Moonbase::FormattedText,
            inbox_id: String,
            subject: String,
            to: ::Array[Moonbase::SlackMessageAddressParams],
            type: :slack_message
          }

        class SlackMessageNewConversationCreateParams < Moonbase::Internal::Type::BaseModel
          attr_accessor body: Moonbase::FormattedText

          attr_accessor inbox_id: String

          attr_accessor subject: String

          attr_accessor to: ::Array[Moonbase::SlackMessageAddressParams]

          attr_accessor type: :slack_message

          def initialize: (
            body: Moonbase::FormattedText,
            inbox_id: String,
            subject: String,
            to: ::Array[Moonbase::SlackMessageAddressParams],
            ?type: :slack_message
          ) -> void

          def to_hash: -> {
            body: Moonbase::FormattedText,
            inbox_id: String,
            subject: String,
            to: ::Array[Moonbase::SlackMessageAddressParams],
            type: :slack_message
          }
        end

        type email_message_reply_create_params =
          {
            body: Moonbase::FormattedText,
            conversation_id: String,
            inbox_id: String,
            type: :email_message,
            bcc: ::Array[Moonbase::EmailMessageAddressParams],
            cc: ::Array[Moonbase::EmailMessageAddressParams],
            to: ::Array[Moonbase::EmailMessageAddressParams]
          }

        class EmailMessageReplyCreateParams < Moonbase::Internal::Type::BaseModel
          attr_accessor body: Moonbase::FormattedText

          attr_accessor conversation_id: String

          attr_accessor inbox_id: String

          attr_accessor type: :email_message

          attr_reader bcc: ::Array[Moonbase::EmailMessageAddressParams]?

          def bcc=: (
            ::Array[Moonbase::EmailMessageAddressParams]
          ) -> ::Array[Moonbase::EmailMessageAddressParams]

          attr_reader cc: ::Array[Moonbase::EmailMessageAddressParams]?

          def cc=: (
            ::Array[Moonbase::EmailMessageAddressParams]
          ) -> ::Array[Moonbase::EmailMessageAddressParams]

          attr_reader to: ::Array[Moonbase::EmailMessageAddressParams]?

          def to=: (
            ::Array[Moonbase::EmailMessageAddressParams]
          ) -> ::Array[Moonbase::EmailMessageAddressParams]

          def initialize: (
            body: Moonbase::FormattedText,
            conversation_id: String,
            inbox_id: String,
            ?bcc: ::Array[Moonbase::EmailMessageAddressParams],
            ?cc: ::Array[Moonbase::EmailMessageAddressParams],
            ?to: ::Array[Moonbase::EmailMessageAddressParams],
            ?type: :email_message
          ) -> void

          def to_hash: -> {
            body: Moonbase::FormattedText,
            conversation_id: String,
            inbox_id: String,
            type: :email_message,
            bcc: ::Array[Moonbase::EmailMessageAddressParams],
            cc: ::Array[Moonbase::EmailMessageAddressParams],
            to: ::Array[Moonbase::EmailMessageAddressParams]
          }
        end

        type slack_message_reply_create_params =
          {
            body: Moonbase::FormattedText,
            conversation_id: String,
            inbox_id: String,
            type: :slack_message,
            to: ::Array[Moonbase::SlackMessageAddressParams]
          }

        class SlackMessageReplyCreateParams < Moonbase::Internal::Type::BaseModel
          attr_accessor body: Moonbase::FormattedText

          attr_accessor conversation_id: String

          attr_accessor inbox_id: String

          attr_accessor type: :slack_message

          attr_reader to: ::Array[Moonbase::SlackMessageAddressParams]?

          def to=: (
            ::Array[Moonbase::SlackMessageAddressParams]
          ) -> ::Array[Moonbase::SlackMessageAddressParams]

          def initialize: (
            body: Moonbase::FormattedText,
            conversation_id: String,
            inbox_id: String,
            ?to: ::Array[Moonbase::SlackMessageAddressParams],
            ?type: :slack_message
          ) -> void

          def to_hash: -> {
            body: Moonbase::FormattedText,
            conversation_id: String,
            inbox_id: String,
            type: :slack_message,
            to: ::Array[Moonbase::SlackMessageAddressParams]
          }
        end

        def self?.variants: -> ::Array[Moonbase::Models::InboxMessageCreateParams::message]
      end
    end
  end
end
