module Moonbase
  module Models
    type inbox_retrieve_params =
      { include: Moonbase::Models::InboxRetrieveParams::include_ }
      & Moonbase::Internal::Type::request_parameters

    class InboxRetrieveParams < Moonbase::Internal::Type::BaseModel
      extend Moonbase::Internal::Type::RequestParameters::Converter
      include Moonbase::Internal::Type::RequestParameters

      attr_reader include: Moonbase::Models::InboxRetrieveParams::include_?

      def include=: (
        Moonbase::Models::InboxRetrieveParams::include_
      ) -> Moonbase::Models::InboxRetrieveParams::include_

      def initialize: (
        ?include: Moonbase::Models::InboxRetrieveParams::include_,
        ?request_options: Moonbase::request_opts
      ) -> void

      def to_hash: -> {
        include: Moonbase::Models::InboxRetrieveParams::include_,
        request_options: Moonbase::RequestOptions
      }

      type include_ = :tagset

      module Include
        extend Moonbase::Internal::Type::Enum

        TAGSET: :tagset

        def self?.values: -> ::Array[Moonbase::Models::InboxRetrieveParams::include_]
      end
    end
  end
end
