module Moonbase
  module Models
    type inbox_message_create_response =
      Moonbase::EmailMessage | Moonbase::SlackMessage

    module InboxMessageCreateResponse
      extend Moonbase::Internal::Type::Union

      def self?.variants: -> ::Array[Moonbase::Models::inbox_message_create_response]
    end
  end
end
