module Moonbase
  module Models
    type inbox_message_create_params =
      {
        body: Moonbase::FormattedText,
        inbox_id: String,
        bcc: ::Array[Moonbase::EmailMessageAddressParams],
        cc: ::Array[Moonbase::EmailMessageAddressParams],
        conversation_id: String,
        subject: String,
        to: ::Array[Moonbase::EmailMessageAddressParams]
      }
      & Moonbase::Internal::Type::request_parameters

    class InboxMessageCreateParams < Moonbase::Internal::Type::BaseModel
      extend Moonbase::Internal::Type::RequestParameters::Converter
      include Moonbase::Internal::Type::RequestParameters

      attr_accessor body: Moonbase::FormattedText

      attr_accessor inbox_id: String

      attr_reader bcc: ::Array[Moonbase::EmailMessageAddressParams]?

      def bcc=: (
        ::Array[Moonbase::EmailMessageAddressParams]
      ) -> ::Array[Moonbase::EmailMessageAddressParams]

      attr_reader cc: ::Array[Moonbase::EmailMessageAddressParams]?

      def cc=: (
        ::Array[Moonbase::EmailMessageAddressParams]
      ) -> ::Array[Moonbase::EmailMessageAddressParams]

      attr_reader conversation_id: String?

      def conversation_id=: (String) -> String

      attr_reader subject: String?

      def subject=: (String) -> String

      attr_reader to: ::Array[Moonbase::EmailMessageAddressParams]?

      def to=: (
        ::Array[Moonbase::EmailMessageAddressParams]
      ) -> ::Array[Moonbase::EmailMessageAddressParams]

      def initialize: (
        body: Moonbase::FormattedText,
        inbox_id: String,
        ?bcc: ::Array[Moonbase::EmailMessageAddressParams],
        ?cc: ::Array[Moonbase::EmailMessageAddressParams],
        ?conversation_id: String,
        ?subject: String,
        ?to: ::Array[Moonbase::EmailMessageAddressParams],
        ?request_options: Moonbase::request_opts
      ) -> void

      def to_hash: -> {
        body: Moonbase::FormattedText,
        inbox_id: String,
        bcc: ::Array[Moonbase::EmailMessageAddressParams],
        cc: ::Array[Moonbase::EmailMessageAddressParams],
        conversation_id: String,
        subject: String,
        to: ::Array[Moonbase::EmailMessageAddressParams],
        request_options: Moonbase::RequestOptions
      }
    end
  end
end
