module Moonbase
  module Models
    type inbox_message_update_params =
      {
        id: String,
        lock_version: Integer,
        bcc: ::Array[Moonbase::EmailMessageAddressParams],
        body: Moonbase::FormattedText,
        cc: ::Array[Moonbase::EmailMessageAddressParams],
        subject: String,
        to: ::Array[Moonbase::EmailMessageAddressParams]
      }
      & Moonbase::Internal::Type::request_parameters

    class InboxMessageUpdateParams < Moonbase::Internal::Type::BaseModel
      extend Moonbase::Internal::Type::RequestParameters::Converter
      include Moonbase::Internal::Type::RequestParameters

      attr_accessor id: String

      attr_accessor lock_version: Integer

      attr_reader bcc: ::Array[Moonbase::EmailMessageAddressParams]?

      def bcc=: (
        ::Array[Moonbase::EmailMessageAddressParams]
      ) -> ::Array[Moonbase::EmailMessageAddressParams]

      attr_reader body: Moonbase::FormattedText?

      def body=: (Moonbase::FormattedText) -> Moonbase::FormattedText

      attr_reader cc: ::Array[Moonbase::EmailMessageAddressParams]?

      def cc=: (
        ::Array[Moonbase::EmailMessageAddressParams]
      ) -> ::Array[Moonbase::EmailMessageAddressParams]

      attr_reader subject: String?

      def subject=: (String) -> String

      attr_reader to: ::Array[Moonbase::EmailMessageAddressParams]?

      def to=: (
        ::Array[Moonbase::EmailMessageAddressParams]
      ) -> ::Array[Moonbase::EmailMessageAddressParams]

      def initialize: (
        id: String,
        lock_version: Integer,
        ?bcc: ::Array[Moonbase::EmailMessageAddressParams],
        ?body: Moonbase::FormattedText,
        ?cc: ::Array[Moonbase::EmailMessageAddressParams],
        ?subject: String,
        ?to: ::Array[Moonbase::EmailMessageAddressParams],
        ?request_options: Moonbase::request_opts
      ) -> void

      def to_hash: -> {
        id: String,
        lock_version: Integer,
        bcc: ::Array[Moonbase::EmailMessageAddressParams],
        body: Moonbase::FormattedText,
        cc: ::Array[Moonbase::EmailMessageAddressParams],
        subject: String,
        to: ::Array[Moonbase::EmailMessageAddressParams],
        request_options: Moonbase::RequestOptions
      }
    end
  end
end
