module Moonbase
  module Models
    type inbox_message_list_params =
      {
        after: String,
        before: String,
        conversation_id: Moonbase::InboxMessageListParams::ConversationID,
        inbox_id: Moonbase::InboxMessageListParams::InboxID,
        limit: Integer
      }
      & Moonbase::Internal::Type::request_parameters

    class InboxMessageListParams < Moonbase::Internal::Type::BaseModel
      extend Moonbase::Internal::Type::RequestParameters::Converter
      include Moonbase::Internal::Type::RequestParameters

      attr_reader after: String?

      def after=: (String) -> String

      attr_reader before: String?

      def before=: (String) -> String

      attr_reader conversation_id: Moonbase::InboxMessageListParams::ConversationID?

      def conversation_id=: (
        Moonbase::InboxMessageListParams::ConversationID
      ) -> Moonbase::InboxMessageListParams::ConversationID

      attr_reader inbox_id: Moonbase::InboxMessageListParams::InboxID?

      def inbox_id=: (
        Moonbase::InboxMessageListParams::InboxID
      ) -> Moonbase::InboxMessageListParams::InboxID

      attr_reader limit: Integer?

      def limit=: (Integer) -> Integer

      def initialize: (
        ?after: String,
        ?before: String,
        ?conversation_id: Moonbase::InboxMessageListParams::ConversationID,
        ?inbox_id: Moonbase::InboxMessageListParams::InboxID,
        ?limit: Integer,
        ?request_options: Moonbase::request_opts
      ) -> void

      def to_hash: -> {
        after: String,
        before: String,
        conversation_id: Moonbase::InboxMessageListParams::ConversationID,
        inbox_id: Moonbase::InboxMessageListParams::InboxID,
        limit: Integer,
        request_options: Moonbase::RequestOptions
      }

      type conversation_id = { eq: String }

      class ConversationID < Moonbase::Internal::Type::BaseModel
        attr_reader eq: String?

        def eq=: (String) -> String

        def initialize: (?eq: String) -> void

        def to_hash: -> { eq: String }
      end

      type inbox_id = { eq: String }

      class InboxID < Moonbase::Internal::Type::BaseModel
        attr_reader eq: String?

        def eq=: (String) -> String

        def initialize: (?eq: String) -> void

        def to_hash: -> { eq: String }
      end
    end
  end
end
