module Moonbase
  module Models
    type inbox =
      {
        id: String,
        created_at: Time,
        name: String,
        tagsets: ::Array[Moonbase::TagsetPointer],
        type: :inbox,
        updated_at: Time,
        can_read: bool
      }

    class Inbox < Moonbase::Internal::Type::BaseModel
      attr_accessor id: String

      attr_accessor created_at: Time

      attr_accessor name: String

      attr_accessor tagsets: ::Array[Moonbase::TagsetPointer]

      attr_accessor type: :inbox

      attr_accessor updated_at: Time

      attr_reader can_read: bool?

      def can_read=: (bool) -> bool

      def initialize: (
        id: String,
        created_at: Time,
        name: String,
        tagsets: ::Array[Moonbase::TagsetPointer],
        updated_at: Time,
        ?can_read: bool,
        ?type: :inbox
      ) -> void

      def to_hash: -> {
        id: String,
        created_at: Time,
        name: String,
        tagsets: ::Array[Moonbase::TagsetPointer],
        type: :inbox,
        updated_at: Time,
        can_read: bool
      }
    end
  end
end
