module Moonbase
  module Models
    type inbox_message_list_params =
      {
        after: String,
        before: String,
        filter: Moonbase::InboxMessageListParams::Filter,
        include: ::Array[Moonbase::Models::InboxMessageListParams::include_],
        limit: Integer
      }
      & Moonbase::Internal::Type::request_parameters

    class InboxMessageListParams < Moonbase::Internal::Type::BaseModel
      extend Moonbase::Internal::Type::RequestParameters::Converter
      include Moonbase::Internal::Type::RequestParameters

      attr_reader after: String?

      def after=: (String) -> String

      attr_reader before: String?

      def before=: (String) -> String

      attr_reader filter: Moonbase::InboxMessageListParams::Filter?

      def filter=: (
        Moonbase::InboxMessageListParams::Filter
      ) -> Moonbase::InboxMessageListParams::Filter

      attr_reader include: ::Array[Moonbase::Models::InboxMessageListParams::include_]?

      def include=: (
        ::Array[Moonbase::Models::InboxMessageListParams::include_]
      ) -> ::Array[Moonbase::Models::InboxMessageListParams::include_]

      attr_reader limit: Integer?

      def limit=: (Integer) -> Integer

      def initialize: (
        ?after: String,
        ?before: String,
        ?filter: Moonbase::InboxMessageListParams::Filter,
        ?include: ::Array[Moonbase::Models::InboxMessageListParams::include_],
        ?limit: Integer,
        ?request_options: Moonbase::request_opts
      ) -> void

      def to_hash: -> {
        after: String,
        before: String,
        filter: Moonbase::InboxMessageListParams::Filter,
        include: ::Array[Moonbase::Models::InboxMessageListParams::include_],
        limit: Integer,
        request_options: Moonbase::RequestOptions
      }

      type filter =
        {
          conversation_id: Moonbase::InboxMessageListParams::Filter::ConversationID,
          inbox_id: Moonbase::InboxMessageListParams::Filter::InboxID
        }

      class Filter < Moonbase::Internal::Type::BaseModel
        attr_reader conversation_id: Moonbase::InboxMessageListParams::Filter::ConversationID?

        def conversation_id=: (
          Moonbase::InboxMessageListParams::Filter::ConversationID
        ) -> Moonbase::InboxMessageListParams::Filter::ConversationID

        attr_reader inbox_id: Moonbase::InboxMessageListParams::Filter::InboxID?

        def inbox_id=: (
          Moonbase::InboxMessageListParams::Filter::InboxID
        ) -> Moonbase::InboxMessageListParams::Filter::InboxID

        def initialize: (
          ?conversation_id: Moonbase::InboxMessageListParams::Filter::ConversationID,
          ?inbox_id: Moonbase::InboxMessageListParams::Filter::InboxID
        ) -> void

        def to_hash: -> {
          conversation_id: Moonbase::InboxMessageListParams::Filter::ConversationID,
          inbox_id: Moonbase::InboxMessageListParams::Filter::InboxID
        }

        type conversation_id = { eq: String }

        class ConversationID < Moonbase::Internal::Type::BaseModel
          attr_reader eq: String?

          def eq=: (String) -> String

          def initialize: (?eq: String) -> void

          def to_hash: -> { eq: String }
        end

        type inbox_id = { eq: String }

        class InboxID < Moonbase::Internal::Type::BaseModel
          attr_reader eq: String?

          def eq=: (String) -> String

          def initialize: (?eq: String) -> void

          def to_hash: -> { eq: String }
        end
      end

      type include_ = :addresses | :attachments | :conversation

      module Include
        extend Moonbase::Internal::Type::Enum

        ADDRESSES: :addresses
        ATTACHMENTS: :attachments
        CONVERSATION: :conversation

        def self?.values: -> ::Array[Moonbase::Models::InboxMessageListParams::include_]
      end
    end
  end
end
