module Moonbase
  module Models
    type inbox_message_update_params =
      {
        lock_version: Integer,
        bcc: ::Array[Moonbase::InboxMessageUpdateParams::Bcc],
        body: Moonbase::FormattedText,
        cc: ::Array[Moonbase::InboxMessageUpdateParams::Cc],
        subject: String,
        to: ::Array[Moonbase::InboxMessageUpdateParams::To]
      }
      & Moonbase::Internal::Type::request_parameters

    class InboxMessageUpdateParams < Moonbase::Internal::Type::BaseModel
      extend Moonbase::Internal::Type::RequestParameters::Converter
      include Moonbase::Internal::Type::RequestParameters

      attr_accessor lock_version: Integer

      attr_reader bcc: ::Array[Moonbase::InboxMessageUpdateParams::Bcc]?

      def bcc=: (
        ::Array[Moonbase::InboxMessageUpdateParams::Bcc]
      ) -> ::Array[Moonbase::InboxMessageUpdateParams::Bcc]

      attr_reader body: Moonbase::FormattedText?

      def body=: (Moonbase::FormattedText) -> Moonbase::FormattedText

      attr_reader cc: ::Array[Moonbase::InboxMessageUpdateParams::Cc]?

      def cc=: (
        ::Array[Moonbase::InboxMessageUpdateParams::Cc]
      ) -> ::Array[Moonbase::InboxMessageUpdateParams::Cc]

      attr_reader subject: String?

      def subject=: (String) -> String

      attr_reader to: ::Array[Moonbase::InboxMessageUpdateParams::To]?

      def to=: (
        ::Array[Moonbase::InboxMessageUpdateParams::To]
      ) -> ::Array[Moonbase::InboxMessageUpdateParams::To]

      def initialize: (
        lock_version: Integer,
        ?bcc: ::Array[Moonbase::InboxMessageUpdateParams::Bcc],
        ?body: Moonbase::FormattedText,
        ?cc: ::Array[Moonbase::InboxMessageUpdateParams::Cc],
        ?subject: String,
        ?to: ::Array[Moonbase::InboxMessageUpdateParams::To],
        ?request_options: Moonbase::request_opts
      ) -> void

      def to_hash: -> {
        lock_version: Integer,
        bcc: ::Array[Moonbase::InboxMessageUpdateParams::Bcc],
        body: Moonbase::FormattedText,
        cc: ::Array[Moonbase::InboxMessageUpdateParams::Cc],
        subject: String,
        to: ::Array[Moonbase::InboxMessageUpdateParams::To],
        request_options: Moonbase::RequestOptions
      }

      type bcc = { email: String, name: String }

      class Bcc < Moonbase::Internal::Type::BaseModel
        attr_accessor email: String

        attr_reader name: String?

        def name=: (String) -> String

        def initialize: (email: String, ?name: String) -> void

        def to_hash: -> { email: String, name: String }
      end

      type cc = { email: String, name: String }

      class Cc < Moonbase::Internal::Type::BaseModel
        attr_accessor email: String

        attr_reader name: String?

        def name=: (String) -> String

        def initialize: (email: String, ?name: String) -> void

        def to_hash: -> { email: String, name: String }
      end

      type to = { email: String, name: String }

      class To < Moonbase::Internal::Type::BaseModel
        attr_accessor email: String

        attr_reader name: String?

        def name=: (String) -> String

        def initialize: (email: String, ?name: String) -> void

        def to_hash: -> { email: String, name: String }
      end
    end
  end
end
