module Moonbase
  module Models
    type item_update_params =
      {
        values: ::Hash[Symbol, Moonbase::Models::field_value],
        update_many_strategy: Moonbase::Models::ItemUpdateParams::update_many_strategy,
        update_one_strategy: Moonbase::Models::ItemUpdateParams::update_one_strategy
      }
      & Moonbase::Internal::Type::request_parameters

    class ItemUpdateParams < Moonbase::Internal::Type::BaseModel
      extend Moonbase::Internal::Type::RequestParameters::Converter
      include Moonbase::Internal::Type::RequestParameters

      attr_accessor values: ::Hash[Symbol, Moonbase::Models::field_value]

      attr_reader update_many_strategy: Moonbase::Models::ItemUpdateParams::update_many_strategy?

      def update_many_strategy=: (
        Moonbase::Models::ItemUpdateParams::update_many_strategy
      ) -> Moonbase::Models::ItemUpdateParams::update_many_strategy

      attr_reader update_one_strategy: Moonbase::Models::ItemUpdateParams::update_one_strategy?

      def update_one_strategy=: (
        Moonbase::Models::ItemUpdateParams::update_one_strategy
      ) -> Moonbase::Models::ItemUpdateParams::update_one_strategy

      def initialize: (
        values: ::Hash[Symbol, Moonbase::Models::field_value],
        ?update_many_strategy: Moonbase::Models::ItemUpdateParams::update_many_strategy,
        ?update_one_strategy: Moonbase::Models::ItemUpdateParams::update_one_strategy,
        ?request_options: Moonbase::request_opts
      ) -> void

      def to_hash: -> {
        values: ::Hash[Symbol, Moonbase::Models::field_value],
        update_many_strategy: Moonbase::Models::ItemUpdateParams::update_many_strategy,
        update_one_strategy: Moonbase::Models::ItemUpdateParams::update_one_strategy,
        request_options: Moonbase::RequestOptions
      }

      type update_many_strategy = :replace | :preserve | :merge

      module UpdateManyStrategy
        extend Moonbase::Internal::Type::Enum

        REPLACE: :replace
        PRESERVE: :preserve
        MERGE: :merge

        def self?.values: -> ::Array[Moonbase::Models::ItemUpdateParams::update_many_strategy]
      end

      type update_one_strategy = :replace | :preserve

      module UpdateOneStrategy
        extend Moonbase::Internal::Type::Enum

        REPLACE: :replace
        PRESERVE: :preserve

        def self?.values: -> ::Array[Moonbase::Models::ItemUpdateParams::update_one_strategy]
      end
    end
  end
end
