module Moonbase
  module Models
    type meeting_list_params =
      {
        after: String,
        before: String,
        i_cal_uid: Moonbase::MeetingListParams::ICalUid,
        limit: Integer
      }
      & Moonbase::Internal::Type::request_parameters

    class MeetingListParams < Moonbase::Internal::Type::BaseModel
      extend Moonbase::Internal::Type::RequestParameters::Converter
      include Moonbase::Internal::Type::RequestParameters

      attr_reader after: String?

      def after=: (String) -> String

      attr_reader before: String?

      def before=: (String) -> String

      attr_reader i_cal_uid: Moonbase::MeetingListParams::ICalUid?

      def i_cal_uid=: (
        Moonbase::MeetingListParams::ICalUid
      ) -> Moonbase::MeetingListParams::ICalUid

      attr_reader limit: Integer?

      def limit=: (Integer) -> Integer

      def initialize: (
        ?after: String,
        ?before: String,
        ?i_cal_uid: Moonbase::MeetingListParams::ICalUid,
        ?limit: Integer,
        ?request_options: Moonbase::request_opts
      ) -> void

      def to_hash: -> {
        after: String,
        before: String,
        i_cal_uid: Moonbase::MeetingListParams::ICalUid,
        limit: Integer,
        request_options: Moonbase::RequestOptions
      }

      type i_cal_uid = { eq: String }

      class ICalUid < Moonbase::Internal::Type::BaseModel
        attr_reader eq: String?

        def eq=: (String) -> String

        def initialize: (?eq: String) -> void

        def to_hash: -> { eq: String }
      end
    end
  end
end
