module Moonbase
  module Models
    type meeting =
      {
        id: String,
        created_at: Time,
        end_at: Time,
        i_cal_uid: String,
        provider_id: String,
        start_at: Time,
        time_zone: String,
        type: :meeting,
        updated_at: Time,
        attendees: ::Array[Moonbase::Attendee],
        description: String,
        duration: Float,
        location: String,
        organizer: Moonbase::Organizer,
        provider_uri: String,
        recording_url: String,
        summary_ante: String,
        summary_post: String,
        title: String,
        transcript_url: String
      }

    class Meeting < Moonbase::Internal::Type::BaseModel
      attr_accessor id: String

      attr_accessor created_at: Time

      attr_accessor end_at: Time

      attr_accessor i_cal_uid: String

      attr_accessor provider_id: String

      attr_accessor start_at: Time

      attr_accessor time_zone: String

      attr_accessor type: :meeting

      attr_accessor updated_at: Time

      attr_reader attendees: ::Array[Moonbase::Attendee]?

      def attendees=: (
        ::Array[Moonbase::Attendee]
      ) -> ::Array[Moonbase::Attendee]

      attr_reader description: String?

      def description=: (String) -> String

      attr_reader duration: Float?

      def duration=: (Float) -> Float

      attr_reader location: String?

      def location=: (String) -> String

      attr_reader organizer: Moonbase::Organizer?

      def organizer=: (Moonbase::Organizer) -> Moonbase::Organizer

      attr_reader provider_uri: String?

      def provider_uri=: (String) -> String

      attr_reader recording_url: String?

      def recording_url=: (String) -> String

      attr_reader summary_ante: String?

      def summary_ante=: (String) -> String

      attr_reader summary_post: String?

      def summary_post=: (String) -> String

      attr_reader title: String?

      def title=: (String) -> String

      attr_reader transcript_url: String?

      def transcript_url=: (String) -> String

      def initialize: (
        id: String,
        created_at: Time,
        end_at: Time,
        i_cal_uid: String,
        provider_id: String,
        start_at: Time,
        time_zone: String,
        updated_at: Time,
        ?attendees: ::Array[Moonbase::Attendee],
        ?description: String,
        ?duration: Float,
        ?location: String,
        ?organizer: Moonbase::Organizer,
        ?provider_uri: String,
        ?recording_url: String,
        ?summary_ante: String,
        ?summary_post: String,
        ?title: String,
        ?transcript_url: String,
        ?type: :meeting
      ) -> void

      def to_hash: -> {
        id: String,
        created_at: Time,
        end_at: Time,
        i_cal_uid: String,
        provider_id: String,
        start_at: Time,
        time_zone: String,
        type: :meeting,
        updated_at: Time,
        attendees: ::Array[Moonbase::Attendee],
        description: String,
        duration: Float,
        location: String,
        organizer: Moonbase::Organizer,
        provider_uri: String,
        recording_url: String,
        summary_ante: String,
        summary_post: String,
        title: String,
        transcript_url: String
      }
    end
  end
end
