module Moonbase
  module Models
    type message_attachment_create_params =
      { file: Moonbase::Internal::file_input, file_id: String }

    class MessageAttachmentCreateParams < Moonbase::Internal::Type::BaseModel
      attr_reader file: Moonbase::Internal::file_input?

      def file=: (
        Moonbase::Internal::file_input
      ) -> Moonbase::Internal::file_input

      attr_reader file_id: String?

      def file_id=: (String) -> String

      def initialize: (
        ?file: Moonbase::Internal::file_input,
        ?file_id: String
      ) -> void

      def to_hash: -> { file: Moonbase::Internal::file_input, file_id: String }
    end
  end
end
