module Moonbase
  module Models
    type monetary_value =
      { data: Moonbase::MonetaryValue::Data, type: :"value/number/monetary" }

    class MonetaryValue < Moonbase::Internal::Type::BaseModel
      attr_accessor data: Moonbase::MonetaryValue::Data

      attr_accessor type: :"value/number/monetary"

      def initialize: (
        data: Moonbase::MonetaryValue::Data,
        ?type: :"value/number/monetary"
      ) -> void

      def to_hash: -> {
        data: Moonbase::MonetaryValue::Data,
        type: :"value/number/monetary"
      }

      type data = { currency: String, in_minor_units: Integer }

      class Data < Moonbase::Internal::Type::BaseModel
        attr_accessor currency: String

        attr_accessor in_minor_units: Integer

        def initialize: (currency: String, in_minor_units: Integer) -> void

        def to_hash: -> { currency: String, in_minor_units: Integer }
      end
    end
  end
end
