module Moonbase
  module Models
    type moonbase_file =
      {
        id: String,
        created_at: Time,
        download_url: String,
        filename: String,
        name: String,
        size: Float,
        type: :file,
        updated_at: Time
      }

    class MoonbaseFile < Moonbase::Internal::Type::BaseModel
      attr_accessor id: String

      attr_accessor created_at: Time

      attr_accessor download_url: String

      attr_accessor filename: String

      attr_accessor name: String

      attr_accessor size: Float

      attr_accessor type: :file

      attr_accessor updated_at: Time

      def initialize: (
        id: String,
        created_at: Time,
        download_url: String,
        filename: String,
        name: String,
        size: Float,
        updated_at: Time,
        ?type: :file
      ) -> void

      def to_hash: -> {
        id: String,
        created_at: Time,
        download_url: String,
        filename: String,
        name: String,
        size: Float,
        type: :file,
        updated_at: Time
      }
    end
  end
end
