module Moonbase
  module Models
    type multi_line_text_value =
      { data: String, type: :"value/text/multi_line" }

    class MultiLineTextValue < Moonbase::Internal::Type::BaseModel
      attr_accessor data: String

      attr_accessor type: :"value/text/multi_line"

      def initialize: (data: String, ?type: :"value/text/multi_line") -> void

      def to_hash: -> { data: String, type: :"value/text/multi_line" }
    end
  end
end
