module Moonbase
  module Models
    type note_update_params =
      { body: Moonbase::FormattedText, lock_version: Integer }
      & Moonbase::Internal::Type::request_parameters

    class NoteUpdateParams < Moonbase::Internal::Type::BaseModel
      extend Moonbase::Internal::Type::RequestParameters::Converter
      include Moonbase::Internal::Type::RequestParameters

      attr_accessor body: Moonbase::FormattedText

      attr_accessor lock_version: Integer

      def initialize: (
        body: Moonbase::FormattedText,
        lock_version: Integer,
        ?request_options: Moonbase::request_opts
      ) -> void

      def to_hash: -> {
        body: Moonbase::FormattedText,
        lock_version: Integer,
        request_options: Moonbase::RequestOptions
      }
    end
  end
end
