module Moonbase
  module Models
    type note =
      {
        id: String,
        body: Moonbase::FormattedText,
        created_at: Time,
        type: :note,
        updated_at: Time,
        summary: String,
        title: String
      }

    class Note < Moonbase::Internal::Type::BaseModel
      attr_accessor id: String

      attr_accessor body: Moonbase::FormattedText

      attr_accessor created_at: Time

      attr_accessor type: :note

      attr_accessor updated_at: Time

      attr_reader summary: String?

      def summary=: (String) -> String

      attr_reader title: String?

      def title=: (String) -> String

      def initialize: (
        id: String,
        body: Moonbase::FormattedText,
        created_at: Time,
        updated_at: Time,
        ?summary: String,
        ?title: String,
        ?type: :note
      ) -> void

      def to_hash: -> {
        id: String,
        body: Moonbase::FormattedText,
        created_at: Time,
        type: :note,
        updated_at: Time,
        summary: String,
        title: String
      }
    end
  end
end
