module Moonbase
  module Models
    type note =
      {
        id: String,
        associations: ::Array[Moonbase::Pointer],
        body: Moonbase::FormattedText,
        created_at: Time,
        lock_version: Integer,
        type: :note,
        updated_at: Time,
        creator: Moonbase::ItemPointer?,
        summary: String,
        title: String
      }

    class Note < Moonbase::Internal::Type::BaseModel
      attr_accessor id: String

      attr_accessor associations: ::Array[Moonbase::Pointer]

      attr_accessor body: Moonbase::FormattedText

      attr_accessor created_at: Time

      attr_accessor lock_version: Integer

      attr_accessor type: :note

      attr_accessor updated_at: Time

      attr_accessor creator: Moonbase::ItemPointer?

      attr_reader summary: String?

      def summary=: (String) -> String

      attr_reader title: String?

      def title=: (String) -> String

      def initialize: (
        id: String,
        associations: ::Array[Moonbase::Pointer],
        body: Moonbase::FormattedText,
        created_at: Time,
        lock_version: Integer,
        updated_at: Time,
        ?creator: Moonbase::ItemPointer?,
        ?summary: String,
        ?title: String,
        ?type: :note
      ) -> void

      def to_hash: -> {
        id: String,
        associations: ::Array[Moonbase::Pointer],
        body: Moonbase::FormattedText,
        created_at: Time,
        lock_version: Integer,
        type: :note,
        updated_at: Time,
        creator: Moonbase::ItemPointer?,
        summary: String,
        title: String
      }
    end
  end
end
