module Moonbase
  module Models
    type organizer =
      {
        id: String,
        email: String,
        type: :meeting_organizer,
        organization: Moonbase::ItemPointer,
        person: Moonbase::ItemPointer
      }

    class Organizer < Moonbase::Internal::Type::BaseModel
      attr_accessor id: String

      attr_accessor email: String

      attr_accessor type: :meeting_organizer

      attr_reader organization: Moonbase::ItemPointer?

      def organization=: (Moonbase::ItemPointer) -> Moonbase::ItemPointer

      attr_reader person: Moonbase::ItemPointer?

      def person=: (Moonbase::ItemPointer) -> Moonbase::ItemPointer

      def initialize: (
        id: String,
        email: String,
        ?organization: Moonbase::ItemPointer,
        ?person: Moonbase::ItemPointer,
        ?type: :meeting_organizer
      ) -> void

      def to_hash: -> {
        id: String,
        email: String,
        type: :meeting_organizer,
        organization: Moonbase::ItemPointer,
        person: Moonbase::ItemPointer
      }
    end
  end
end
