module Moonbase
  module Models
    type percentage_value = { data: Float, type: :"value/number/percentage" }

    class PercentageValue < Moonbase::Internal::Type::BaseModel
      attr_accessor data: Float

      attr_accessor type: :"value/number/percentage"

      def initialize: (data: Float, ?type: :"value/number/percentage") -> void

      def to_hash: -> { data: Float, type: :"value/number/percentage" }
    end
  end
end
