module Moonbase
  module Models
    type program_template =
      {
        id: String,
        body: Moonbase::FormattedText,
        created_at: Time,
        subject: String,
        type: :program_template,
        updated_at: Time,
        program: Moonbase::Program
      }

    class ProgramTemplate < Moonbase::Internal::Type::BaseModel
      attr_accessor id: String

      attr_accessor body: Moonbase::FormattedText

      attr_accessor created_at: Time

      attr_accessor subject: String

      attr_accessor type: :program_template

      attr_accessor updated_at: Time

      attr_reader program: Moonbase::Program?

      def program=: (Moonbase::Program) -> Moonbase::Program

      def initialize: (
        id: String,
        body: Moonbase::FormattedText,
        created_at: Time,
        subject: String,
        updated_at: Time,
        ?program: Moonbase::Program,
        ?type: :program_template
      ) -> void

      def to_hash: -> {
        id: String,
        body: Moonbase::FormattedText,
        created_at: Time,
        subject: String,
        type: :program_template,
        updated_at: Time,
        program: Moonbase::Program
      }
    end
  end
end
