module Moonbase
  module Models
    type program =
      {
        id: String,
        created_at: Time,
        status: Moonbase::Models::Program::status,
        track_clicks: bool,
        track_opens: bool,
        trigger: Moonbase::Models::Program::trigger,
        type: :program,
        updated_at: Time,
        activity_metrics: Moonbase::Program::ActivityMetrics,
        display_name: String,
        program_template: Moonbase::ProgramTemplate,
        scheduled_at: Time
      }

    class Program < Moonbase::Internal::Type::BaseModel
      attr_accessor id: String

      attr_accessor created_at: Time

      attr_accessor status: Moonbase::Models::Program::status

      attr_accessor track_clicks: bool

      attr_accessor track_opens: bool

      attr_accessor trigger: Moonbase::Models::Program::trigger

      attr_accessor type: :program

      attr_accessor updated_at: Time

      attr_reader activity_metrics: Moonbase::Program::ActivityMetrics?

      def activity_metrics=: (
        Moonbase::Program::ActivityMetrics
      ) -> Moonbase::Program::ActivityMetrics

      attr_reader display_name: String?

      def display_name=: (String) -> String

      attr_reader program_template: Moonbase::ProgramTemplate?

      def program_template=: (
        Moonbase::ProgramTemplate
      ) -> Moonbase::ProgramTemplate

      attr_reader scheduled_at: Time?

      def scheduled_at=: (Time) -> Time

      def initialize: (
        id: String,
        created_at: Time,
        status: Moonbase::Models::Program::status,
        track_clicks: bool,
        track_opens: bool,
        trigger: Moonbase::Models::Program::trigger,
        updated_at: Time,
        ?activity_metrics: Moonbase::Program::ActivityMetrics,
        ?display_name: String,
        ?program_template: Moonbase::ProgramTemplate,
        ?scheduled_at: Time,
        ?type: :program
      ) -> void

      def to_hash: -> {
        id: String,
        created_at: Time,
        status: Moonbase::Models::Program::status,
        track_clicks: bool,
        track_opens: bool,
        trigger: Moonbase::Models::Program::trigger,
        type: :program,
        updated_at: Time,
        activity_metrics: Moonbase::Program::ActivityMetrics,
        display_name: String,
        program_template: Moonbase::ProgramTemplate,
        scheduled_at: Time
      }

      type status = :draft | :published | :paused | :archived

      module Status
        extend Moonbase::Internal::Type::Enum

        DRAFT: :draft
        PUBLISHED: :published
        PAUSED: :paused
        ARCHIVED: :archived

        def self?.values: -> ::Array[Moonbase::Models::Program::status]
      end

      type trigger = :api | :broadcast

      module Trigger
        extend Moonbase::Internal::Type::Enum

        API: :api
        BROADCAST: :broadcast

        def self?.values: -> ::Array[Moonbase::Models::Program::trigger]
      end

      type activity_metrics =
        {
          bounced: Integer,
          clicked: Integer,
          complained: Integer,
          failed: Integer,
          opened: Integer,
          sent: Integer,
          shielded: Integer,
          unsubscribed: Integer
        }

      class ActivityMetrics < Moonbase::Internal::Type::BaseModel
        attr_accessor bounced: Integer

        attr_accessor clicked: Integer

        attr_accessor complained: Integer

        attr_accessor failed: Integer

        attr_accessor opened: Integer

        attr_accessor sent: Integer

        attr_accessor shielded: Integer

        attr_accessor unsubscribed: Integer

        def initialize: (
          bounced: Integer,
          clicked: Integer,
          complained: Integer,
          failed: Integer,
          opened: Integer,
          sent: Integer,
          shielded: Integer,
          unsubscribed: Integer
        ) -> void

        def to_hash: -> {
          bounced: Integer,
          clicked: Integer,
          complained: Integer,
          failed: Integer,
          opened: Integer,
          sent: Integer,
          shielded: Integer,
          unsubscribed: Integer
        }
      end
    end
  end
end
