module Moonbase
  module Models
    type relation_value =
      { data: Moonbase::ItemPointer, type: :"value/relation" }

    class RelationValue < Moonbase::Internal::Type::BaseModel
      attr_accessor data: Moonbase::ItemPointer

      attr_accessor type: :"value/relation"

      def initialize: (
        data: Moonbase::ItemPointer,
        ?type: :"value/relation"
      ) -> void

      def to_hash: -> { data: Moonbase::ItemPointer, type: :"value/relation" }
    end
  end
end
