module Moonbase
  module Models
    type relation_value = { item: Moonbase::Item, type: :"value/relation" }

    class RelationValue < Moonbase::Internal::Type::BaseModel
      attr_accessor item: Moonbase::Item

      attr_accessor type: :"value/relation"

      def initialize: (item: Moonbase::Item, ?type: :"value/relation") -> void

      def to_hash: -> { item: Moonbase::Item, type: :"value/relation" }
    end
  end
end
