module Moonbase
  module Models
    type relation_field =
      {
        id: String,
        allowed_collections: ::Array[Moonbase::CollectionPointer],
        cardinality: Moonbase::Models::RelationField::cardinality,
        created_at: Time,
        default_values: ::Array[Moonbase::Models::field_default_value],
        kind: Moonbase::Models::RelationField::kind,
        name: String,
        readonly: bool,
        ref: String,
        relation_type: Moonbase::Models::RelationField::relation_type,
        required: bool,
        type: :"field/relation",
        unique: bool,
        updated_at: Time,
        description: String,
        reverse_field_name: String,
        reverse_fields: ::Array[Moonbase::FieldPointer],
        source_field: Moonbase::FieldPointer
      }

    class RelationField < Moonbase::Internal::Type::BaseModel
      attr_accessor id: String

      attr_accessor allowed_collections: ::Array[Moonbase::CollectionPointer]

      attr_accessor cardinality: Moonbase::Models::RelationField::cardinality

      attr_accessor created_at: Time

      attr_accessor default_values: ::Array[Moonbase::Models::field_default_value]

      attr_accessor kind: Moonbase::Models::RelationField::kind

      attr_accessor name: String

      attr_accessor readonly: bool

      attr_accessor ref: String

      attr_accessor relation_type: Moonbase::Models::RelationField::relation_type

      attr_accessor required: bool

      attr_accessor type: :"field/relation"

      attr_accessor unique: bool

      attr_accessor updated_at: Time

      attr_reader description: String?

      def description=: (String) -> String

      attr_reader reverse_field_name: String?

      def reverse_field_name=: (String) -> String

      attr_reader reverse_fields: ::Array[Moonbase::FieldPointer]?

      def reverse_fields=: (
        ::Array[Moonbase::FieldPointer]
      ) -> ::Array[Moonbase::FieldPointer]

      attr_reader source_field: Moonbase::FieldPointer?

      def source_field=: (Moonbase::FieldPointer) -> Moonbase::FieldPointer

      def initialize: (
        id: String,
        allowed_collections: ::Array[Moonbase::CollectionPointer],
        cardinality: Moonbase::Models::RelationField::cardinality,
        created_at: Time,
        default_values: ::Array[Moonbase::Models::field_default_value],
        kind: Moonbase::Models::RelationField::kind,
        name: String,
        readonly: bool,
        ref: String,
        relation_type: Moonbase::Models::RelationField::relation_type,
        required: bool,
        unique: bool,
        updated_at: Time,
        ?description: String,
        ?reverse_field_name: String,
        ?reverse_fields: ::Array[Moonbase::FieldPointer],
        ?source_field: Moonbase::FieldPointer,
        ?type: :"field/relation"
      ) -> void

      def to_hash: -> {
        id: String,
        allowed_collections: ::Array[Moonbase::CollectionPointer],
        cardinality: Moonbase::Models::RelationField::cardinality,
        created_at: Time,
        default_values: ::Array[Moonbase::Models::field_default_value],
        kind: Moonbase::Models::RelationField::kind,
        name: String,
        readonly: bool,
        ref: String,
        relation_type: Moonbase::Models::RelationField::relation_type,
        required: bool,
        type: :"field/relation",
        unique: bool,
        updated_at: Time,
        description: String,
        reverse_field_name: String,
        reverse_fields: ::Array[Moonbase::FieldPointer],
        source_field: Moonbase::FieldPointer
      }

      type cardinality = :one | :many

      module Cardinality
        extend Moonbase::Internal::Type::Enum

        ONE: :one
        MANY: :many

        def self?.values: -> ::Array[Moonbase::Models::RelationField::cardinality]
      end

      type kind = :system | :inverse | :custom

      module Kind
        extend Moonbase::Internal::Type::Enum

        SYSTEM: :system
        INVERSE: :inverse
        CUSTOM: :custom

        def self?.values: -> ::Array[Moonbase::Models::RelationField::kind]
      end

      type relation_type = :one_way | :two_way

      module RelationType
        extend Moonbase::Internal::Type::Enum

        ONE_WAY: :one_way
        TWO_WAY: :two_way

        def self?.values: -> ::Array[Moonbase::Models::RelationField::relation_type]
      end
    end
  end
end
