module Moonbase
  module Models
    type relation_value_param =
      { data: Moonbase::ItemPointerParam, type: :"value/relation" }

    class RelationValueParam < Moonbase::Internal::Type::BaseModel
      attr_accessor data: Moonbase::ItemPointerParam

      attr_accessor type: :"value/relation"

      def initialize: (
        data: Moonbase::ItemPointerParam,
        ?type: :"value/relation"
      ) -> void

      def to_hash: -> {
        data: Moonbase::ItemPointerParam,
        type: :"value/relation"
      }
    end
  end
end
