module Moonbase
  module Models
    type search_response =
      { data: ::Array[Moonbase::Models::SearchResponse::Data], type: :list }

    class SearchResponse < Moonbase::Internal::Type::BaseModel
      attr_accessor data: ::Array[Moonbase::Models::SearchResponse::Data]

      attr_accessor type: :list

      def initialize: (
        data: ::Array[Moonbase::Models::SearchResponse::Data],
        ?type: :list
      ) -> void

      def to_hash: -> {
        data: ::Array[Moonbase::Models::SearchResponse::Data],
        type: :list
      }

      type data =
        {
          data: Moonbase::Models::SearchResponse::Data::data,
          type: :search_result
        }

      class Data < Moonbase::Internal::Type::BaseModel
        attr_accessor data: Moonbase::Models::SearchResponse::Data::data

        attr_accessor type: :search_result

        def initialize: (
          data: Moonbase::Models::SearchResponse::Data::data,
          ?type: :search_result
        ) -> void

        def to_hash: -> {
          data: Moonbase::Models::SearchResponse::Data::data,
          type: :search_result
        }

        type data = Moonbase::Item | Moonbase::MoonbaseFile

        module Data
          extend Moonbase::Internal::Type::Union

          def self?.variants: -> ::Array[Moonbase::Models::SearchResponse::Data::data]
        end
      end
    end
  end
end
