module Moonbase
  module Models
    type single_line_text_value =
      { data: String, type: :"value/text/single_line" }

    class SingleLineTextValue < Moonbase::Internal::Type::BaseModel
      attr_accessor data: String

      attr_accessor type: :"value/text/single_line"

      def initialize: (data: String, ?type: :"value/text/single_line") -> void

      def to_hash: -> { data: String, type: :"value/text/single_line" }
    end
  end
end
