module Moonbase
  module Models
    type single_line_text_value =
      { text: String, type: :"value/text/single_line" }

    class SingleLineTextValue < Moonbase::Internal::Type::BaseModel
      attr_accessor text: String

      attr_accessor type: :"value/text/single_line"

      def initialize: (text: String, ?type: :"value/text/single_line") -> void

      def to_hash: -> { text: String, type: :"value/text/single_line" }
    end
  end
end
