module Moonbase
  module Models
    type social_linked_in_value =
      {
        data: Moonbase::SocialLinkedInValue::Data,
        type: :"value/uri/social_linked_in"
      }

    class SocialLinkedInValue < Moonbase::Internal::Type::BaseModel
      attr_accessor data: Moonbase::SocialLinkedInValue::Data

      attr_accessor type: :"value/uri/social_linked_in"

      def initialize: (
        data: Moonbase::SocialLinkedInValue::Data,
        ?type: :"value/uri/social_linked_in"
      ) -> void

      def to_hash: -> {
        data: Moonbase::SocialLinkedInValue::Data,
        type: :"value/uri/social_linked_in"
      }

      type data = { url: String, username: String }

      class Data < Moonbase::Internal::Type::BaseModel
        attr_accessor url: String

        attr_accessor username: String

        def initialize: (url: String, username: String) -> void

        def to_hash: -> { url: String, username: String }
      end
    end
  end
end
