module Moonbase
  module Models
    type social_x_value =
      { data: Moonbase::SocialXValue::Data, type: :"value/uri/social_x" }

    class SocialXValue < Moonbase::Internal::Type::BaseModel
      attr_accessor data: Moonbase::SocialXValue::Data

      attr_accessor type: :"value/uri/social_x"

      def initialize: (
        data: Moonbase::SocialXValue::Data,
        ?type: :"value/uri/social_x"
      ) -> void

      def to_hash: -> {
        data: Moonbase::SocialXValue::Data,
        type: :"value/uri/social_x"
      }

      type data = { url: String, username: String }

      class Data < Moonbase::Internal::Type::BaseModel
        attr_accessor url: String

        attr_accessor username: String

        def initialize: (url: String, username: String) -> void

        def to_hash: -> { url: String, username: String }
      end
    end
  end
end
