module Moonbase
  module Models
    type tagset =
      {
        id: String,
        created_at: Time,
        name: String,
        tags: ::Array[Moonbase::Tagset::Tag],
        type: :tagset,
        updated_at: Time,
        description: String
      }

    class Tagset < Moonbase::Internal::Type::BaseModel
      attr_accessor id: String

      attr_accessor created_at: Time

      attr_accessor name: String

      attr_accessor tags: ::Array[Moonbase::Tagset::Tag]

      attr_accessor type: :tagset

      attr_accessor updated_at: Time

      attr_reader description: String?

      def description=: (String) -> String

      def initialize: (
        id: String,
        created_at: Time,
        name: String,
        tags: ::Array[Moonbase::Tagset::Tag],
        updated_at: Time,
        ?description: String,
        ?type: :tagset
      ) -> void

      def to_hash: -> {
        id: String,
        created_at: Time,
        name: String,
        tags: ::Array[Moonbase::Tagset::Tag],
        type: :tagset,
        updated_at: Time,
        description: String
      }

      type tag = { id: String, name: String, type: :tag }

      class Tag < Moonbase::Internal::Type::BaseModel
        attr_accessor id: String

        attr_accessor name: String

        attr_accessor type: :tag

        def initialize: (id: String, name: String, ?type: :tag) -> void

        def to_hash: -> { id: String, name: String, type: :tag }
      end
    end
  end
end
