module Moonbase
  module Models
    type tagset =
      {
        id: String,
        created_at: Time,
        name: String,
        tags: ::Array[Moonbase::Tag],
        type: :tagset,
        updated_at: Time,
        description: String
      }

    class Tagset < Moonbase::Internal::Type::BaseModel
      attr_accessor id: String

      attr_accessor created_at: Time

      attr_accessor name: String

      attr_accessor tags: ::Array[Moonbase::Tag]

      attr_accessor type: :tagset

      attr_accessor updated_at: Time

      attr_reader description: String?

      def description=: (String) -> String

      def initialize: (
        id: String,
        created_at: Time,
        name: String,
        tags: ::Array[Moonbase::Tag],
        updated_at: Time,
        ?description: String,
        ?type: :tagset
      ) -> void

      def to_hash: -> {
        id: String,
        created_at: Time,
        name: String,
        tags: ::Array[Moonbase::Tag],
        type: :tagset,
        updated_at: Time,
        description: String
      }
    end
  end
end
