module Moonbase
  module Models
    type telephone_number = { data: String, type: :"value/telephone_number" }

    class TelephoneNumber < Moonbase::Internal::Type::BaseModel
      attr_accessor data: String

      attr_accessor type: :"value/telephone_number"

      def initialize: (data: String, ?type: :"value/telephone_number") -> void

      def to_hash: -> { data: String, type: :"value/telephone_number" }
    end
  end
end
