module Moonbase
  module Models
    type url_value = { data: String, type: :"value/uri/url" }

    class URLValue < Moonbase::Internal::Type::BaseModel
      attr_accessor data: String

      attr_accessor type: :"value/uri/url"

      def initialize: (data: String, ?type: :"value/uri/url") -> void

      def to_hash: -> { data: String, type: :"value/uri/url" }
    end
  end
end
