module Moonbase
  module Models
    type value_param =
      Moonbase::SingleLineTextValue
      | Moonbase::MultiLineTextValue
      | Moonbase::IntegerValue
      | Moonbase::FloatValue
      | Moonbase::MonetaryValue
      | Moonbase::PercentageValue
      | Moonbase::BooleanValue
      | Moonbase::EmailValue
      | Moonbase::URLValue
      | Moonbase::DomainValue
      | Moonbase::ValueParam::ValueUriSocialX
      | Moonbase::ValueParam::ValueUriSocialLinkedIn
      | Moonbase::TelephoneNumber
      | Moonbase::GeoValue
      | Moonbase::DateValue
      | Moonbase::DatetimeValue
      | Moonbase::ChoiceValueParam
      | Moonbase::FunnelStepValueParam
      | Moonbase::RelationValueParam

    module ValueParam
      extend Moonbase::Internal::Type::Union

      type value_uri_social_x =
        {
          data: Moonbase::ValueParam::ValueUriSocialX::Data,
          type: :"value/uri/social_x"
        }

      class ValueUriSocialX < Moonbase::Internal::Type::BaseModel
        attr_accessor data: Moonbase::ValueParam::ValueUriSocialX::Data

        attr_accessor type: :"value/uri/social_x"

        def initialize: (
          data: Moonbase::ValueParam::ValueUriSocialX::Data,
          ?type: :"value/uri/social_x"
        ) -> void

        def to_hash: -> {
          data: Moonbase::ValueParam::ValueUriSocialX::Data,
          type: :"value/uri/social_x"
        }

        type data = { url: String, username: String }

        class Data < Moonbase::Internal::Type::BaseModel
          attr_reader url: String?

          def url=: (String) -> String

          attr_reader username: String?

          def username=: (String) -> String

          def initialize: (?url: String, ?username: String) -> void

          def to_hash: -> { url: String, username: String }
        end
      end

      type value_uri_social_linked_in =
        {
          data: Moonbase::ValueParam::ValueUriSocialLinkedIn::Data,
          type: :"value/uri/social_linked_in"
        }

      class ValueUriSocialLinkedIn < Moonbase::Internal::Type::BaseModel
        attr_accessor data: Moonbase::ValueParam::ValueUriSocialLinkedIn::Data

        attr_accessor type: :"value/uri/social_linked_in"

        def initialize: (
          data: Moonbase::ValueParam::ValueUriSocialLinkedIn::Data,
          ?type: :"value/uri/social_linked_in"
        ) -> void

        def to_hash: -> {
          data: Moonbase::ValueParam::ValueUriSocialLinkedIn::Data,
          type: :"value/uri/social_linked_in"
        }

        type data = { url: String, username: String }

        class Data < Moonbase::Internal::Type::BaseModel
          attr_reader url: String?

          def url=: (String) -> String

          attr_reader username: String?

          def username=: (String) -> String

          def initialize: (?url: String, ?username: String) -> void

          def to_hash: -> { url: String, username: String }
        end
      end

      def self?.variants: -> ::Array[Moonbase::Models::value_param]
    end
  end
end
