module Moonbase
  module Models
    type value =
      Moonbase::SingleLineTextValue
      | Moonbase::MultiLineTextValue
      | Moonbase::IntegerValue
      | Moonbase::FloatValue
      | Moonbase::MonetaryValue
      | Moonbase::PercentageValue
      | Moonbase::BooleanValue
      | Moonbase::EmailValue
      | Moonbase::URLValue
      | Moonbase::DomainValue
      | Moonbase::SocialXValue
      | Moonbase::SocialLinkedInValue
      | Moonbase::TelephoneNumber
      | Moonbase::GeoValue
      | Moonbase::DateValue
      | Moonbase::DatetimeValue
      | Moonbase::Choice
      | Moonbase::FunnelStep
      | Moonbase::RelationValue

    module Value
      extend Moonbase::Internal::Type::Union

      def self?.variants: -> ::Array[Moonbase::Models::value]
    end
  end
end
