module Moonbase
  module Models
    type view =
      {
        id: String,
        created_at: Time,
        name: String,
        type: :view,
        updated_at: Time,
        view_type: Moonbase::Models::View::view_type,
        collection: Moonbase::Collection
      }

    class View < Moonbase::Internal::Type::BaseModel
      attr_accessor id: String

      attr_accessor created_at: Time

      attr_accessor name: String

      attr_accessor type: :view

      attr_accessor updated_at: Time

      attr_accessor view_type: Moonbase::Models::View::view_type

      attr_reader collection: Moonbase::Collection?

      def collection=: (Moonbase::Collection) -> Moonbase::Collection

      def initialize: (
        id: String,
        created_at: Time,
        name: String,
        updated_at: Time,
        view_type: Moonbase::Models::View::view_type,
        ?collection: Moonbase::Collection,
        ?type: :view
      ) -> void

      def to_hash: -> {
        id: String,
        created_at: Time,
        name: String,
        type: :view,
        updated_at: Time,
        view_type: Moonbase::Models::View::view_type,
        collection: Moonbase::Collection
      }

      type view_type = :table | :board

      module ViewType
        extend Moonbase::Internal::Type::Enum

        TABLE: :table
        BOARD: :board

        def self?.values: -> ::Array[Moonbase::Models::View::view_type]
      end
    end
  end
end
