module Moonbase
  module Models
    type view_retrieve_params =
      { include: ::Array[Moonbase::Models::ViewRetrieveParams::include_] }
      & Moonbase::Internal::Type::request_parameters

    class ViewRetrieveParams < Moonbase::Internal::Type::BaseModel
      extend Moonbase::Internal::Type::RequestParameters::Converter
      include Moonbase::Internal::Type::RequestParameters

      attr_reader include: ::Array[Moonbase::Models::ViewRetrieveParams::include_]?

      def include=: (
        ::Array[Moonbase::Models::ViewRetrieveParams::include_]
      ) -> ::Array[Moonbase::Models::ViewRetrieveParams::include_]

      def initialize: (
        ?include: ::Array[Moonbase::Models::ViewRetrieveParams::include_],
        ?request_options: Moonbase::request_opts
      ) -> void

      def to_hash: -> {
        include: ::Array[Moonbase::Models::ViewRetrieveParams::include_],
        request_options: Moonbase::RequestOptions
      }

      type include_ = :collection

      module Include
        extend Moonbase::Internal::Type::Enum

        COLLECTION: :collection

        def self?.values: -> ::Array[Moonbase::Models::ViewRetrieveParams::include_]
      end
    end
  end
end
