module Moonbase
  module Models
    type view_retrieve_response =
      {
        id: String,
        links: Moonbase::Models::ViewRetrieveResponse::Links,
        name: String,
        type: :view,
        collection: Moonbase::Collection,
        view_type: Moonbase::Models::ViewRetrieveResponse::view_type
      }

    class ViewRetrieveResponse < Moonbase::Internal::Type::BaseModel
      attr_accessor id: String

      attr_accessor links: Moonbase::Models::ViewRetrieveResponse::Links

      attr_accessor name: String

      attr_accessor type: :view

      attr_reader collection: Moonbase::Collection?

      def collection=: (Moonbase::Collection) -> Moonbase::Collection

      attr_reader view_type: Moonbase::Models::ViewRetrieveResponse::view_type?

      def view_type=: (
        Moonbase::Models::ViewRetrieveResponse::view_type
      ) -> Moonbase::Models::ViewRetrieveResponse::view_type

      def initialize: (
        id: String,
        links: Moonbase::Models::ViewRetrieveResponse::Links,
        name: String,
        ?collection: Moonbase::Collection,
        ?view_type: Moonbase::Models::ViewRetrieveResponse::view_type,
        ?type: :view
      ) -> void

      def to_hash: -> {
        id: String,
        links: Moonbase::Models::ViewRetrieveResponse::Links,
        name: String,
        type: :view,
        collection: Moonbase::Collection,
        view_type: Moonbase::Models::ViewRetrieveResponse::view_type
      }

      type links = { collection: String, items: String, self_: String }

      class Links < Moonbase::Internal::Type::BaseModel
        attr_accessor collection: String

        attr_accessor items: String

        attr_accessor self_: String

        def initialize: (
          collection: String,
          items: String,
          self_: String
        ) -> void

        def to_hash: -> { collection: String, items: String, self_: String }
      end

      type view_type = :table | :board

      module ViewType
        extend Moonbase::Internal::Type::Enum

        TABLE: :table
        BOARD: :board

        def self?.values: -> ::Array[Moonbase::Models::ViewRetrieveResponse::view_type]
      end
    end
  end
end
