module Moonbase
  module Models
    type webhook_endpoint_update_params =
      {
        status: Moonbase::Models::WebhookEndpointUpdateParams::status,
        subscriptions: ::Array[Moonbase::WebhookEndpointUpdateParams::Subscription],
        url: String
      }
      & Moonbase::Internal::Type::request_parameters

    class WebhookEndpointUpdateParams < Moonbase::Internal::Type::BaseModel
      extend Moonbase::Internal::Type::RequestParameters::Converter
      include Moonbase::Internal::Type::RequestParameters

      attr_reader status: Moonbase::Models::WebhookEndpointUpdateParams::status?

      def status=: (
        Moonbase::Models::WebhookEndpointUpdateParams::status
      ) -> Moonbase::Models::WebhookEndpointUpdateParams::status

      attr_reader subscriptions: ::Array[Moonbase::WebhookEndpointUpdateParams::Subscription]?

      def subscriptions=: (
        ::Array[Moonbase::WebhookEndpointUpdateParams::Subscription]
      ) -> ::Array[Moonbase::WebhookEndpointUpdateParams::Subscription]

      attr_reader url: String?

      def url=: (String) -> String

      def initialize: (
        ?status: Moonbase::Models::WebhookEndpointUpdateParams::status,
        ?subscriptions: ::Array[Moonbase::WebhookEndpointUpdateParams::Subscription],
        ?url: String,
        ?request_options: Moonbase::request_opts
      ) -> void

      def to_hash: -> {
        status: Moonbase::Models::WebhookEndpointUpdateParams::status,
        subscriptions: ::Array[Moonbase::WebhookEndpointUpdateParams::Subscription],
        url: String,
        request_options: Moonbase::RequestOptions
      }

      type status = :disabled | :enabled

      module Status
        extend Moonbase::Internal::Type::Enum

        DISABLED: :disabled
        ENABLED: :enabled

        def self?.values: -> ::Array[Moonbase::Models::WebhookEndpointUpdateParams::status]
      end

      type subscription =
        {
          event_type: Moonbase::Models::WebhookEndpointUpdateParams::Subscription::event_type,
          id: String
        }

      class Subscription < Moonbase::Internal::Type::BaseModel
        attr_accessor event_type: Moonbase::Models::WebhookEndpointUpdateParams::Subscription::event_type

        attr_reader id: String?

        def id=: (String) -> String

        def initialize: (
          event_type: Moonbase::Models::WebhookEndpointUpdateParams::Subscription::event_type,
          ?id: String
        ) -> void

        def to_hash: -> {
          event_type: Moonbase::Models::WebhookEndpointUpdateParams::Subscription::event_type,
          id: String
        }

        type event_type =
          :"activity/call_occurred"
          | :"activity/form_submitted"
          | :"activity/inbox_message_sent"
          | :"activity/item_created"
          | :"activity/item_mentioned"
          | :"activity/item_merged"
          | :"activity/file_created"
          | :"activity/meeting_held"
          | :"activity/meeting_scheduled"
          | :"activity/note_created"
          | :"activity/program_message_bounced"
          | :"activity/program_message_clicked"
          | :"activity/program_message_complained"
          | :"activity/program_message_failed"
          | :"activity/program_message_opened"
          | :"activity/program_message_sent"
          | :"activity/program_message_shielded"
          | :"activity/program_message_unsubscribed"

        module EventType
          extend Moonbase::Internal::Type::Enum

          ACTIVITY_CALL_OCCURRED: :"activity/call_occurred"
          ACTIVITY_FORM_SUBMITTED: :"activity/form_submitted"
          ACTIVITY_INBOX_MESSAGE_SENT: :"activity/inbox_message_sent"
          ACTIVITY_ITEM_CREATED: :"activity/item_created"
          ACTIVITY_ITEM_MENTIONED: :"activity/item_mentioned"
          ACTIVITY_ITEM_MERGED: :"activity/item_merged"
          ACTIVITY_FILE_CREATED: :"activity/file_created"
          ACTIVITY_MEETING_HELD: :"activity/meeting_held"
          ACTIVITY_MEETING_SCHEDULED: :"activity/meeting_scheduled"
          ACTIVITY_NOTE_CREATED: :"activity/note_created"
          ACTIVITY_PROGRAM_MESSAGE_BOUNCED: :"activity/program_message_bounced"
          ACTIVITY_PROGRAM_MESSAGE_CLICKED: :"activity/program_message_clicked"
          ACTIVITY_PROGRAM_MESSAGE_COMPLAINED: :"activity/program_message_complained"
          ACTIVITY_PROGRAM_MESSAGE_FAILED: :"activity/program_message_failed"
          ACTIVITY_PROGRAM_MESSAGE_OPENED: :"activity/program_message_opened"
          ACTIVITY_PROGRAM_MESSAGE_SENT: :"activity/program_message_sent"
          ACTIVITY_PROGRAM_MESSAGE_SHIELDED: :"activity/program_message_shielded"
          ACTIVITY_PROGRAM_MESSAGE_UNSUBSCRIBED: :"activity/program_message_unsubscribed"

          def self?.values: -> ::Array[Moonbase::Models::WebhookEndpointUpdateParams::Subscription::event_type]
        end
      end
    end
  end
end
