module Moonbase
  module Models
    type webhook_endpoint_delete_params =
      {  } & Moonbase::Internal::Type::request_parameters

    class WebhookEndpointDeleteParams < Moonbase::Internal::Type::BaseModel
      extend Moonbase::Internal::Type::RequestParameters::Converter
      include Moonbase::Internal::Type::RequestParameters

      def initialize: (?request_options: Moonbase::request_opts) -> void

      def to_hash: -> { request_options: Moonbase::RequestOptions }
    end
  end
end
