module Moonbase
  module Resources
    class Calls
      def create: (
        direction: Moonbase::Models::CallCreateParams::direction,
        participants: ::Array[Moonbase::CallCreateParams::Participant],
        provider: Moonbase::Models::CallCreateParams::provider,
        provider_id: String,
        provider_status: String,
        start_at: Time,
        ?answered_at: Time,
        ?end_at: Time,
        ?provider_metadata: ::Hash[Symbol, top],
        ?recordings: ::Array[Moonbase::CallCreateParams::Recording],
        ?transcript: Moonbase::CallCreateParams::Transcript,
        ?request_options: Moonbase::request_opts
      ) -> Moonbase::Call

      def retrieve: (
        String id,
        ?include: ::Array[Moonbase::Models::CallRetrieveParams::include_],
        ?request_options: Moonbase::request_opts
      ) -> Moonbase::Call

      def list: (
        ?after: String,
        ?before: String,
        ?limit: Integer,
        ?request_options: Moonbase::request_opts
      ) -> Moonbase::Internal::CursorPage[Moonbase::Call]

      def upsert: (
        direction: Moonbase::Models::CallUpsertParams::direction,
        participants: ::Array[Moonbase::CallUpsertParams::Participant],
        provider: Moonbase::Models::CallUpsertParams::provider,
        provider_id: String,
        provider_status: String,
        start_at: Time,
        ?answered_at: Time,
        ?end_at: Time,
        ?provider_metadata: ::Hash[Symbol, top],
        ?recordings: ::Array[Moonbase::CallUpsertParams::Recording],
        ?transcript: Moonbase::CallUpsertParams::Transcript,
        ?request_options: Moonbase::request_opts
      ) -> Moonbase::Call

      def initialize: (client: Moonbase::Client) -> void
    end
  end
end
