module Moonbase
  module Resources
    class Collections
      attr_reader fields: Moonbase::Resources::Collections::Fields

      attr_reader items: Moonbase::Resources::Collections::Items

      def create: (
        name: String,
        ?description: String,
        ?request_options: Moonbase::request_opts
      ) -> Moonbase::Collection

      def retrieve: (
        String id,
        ?request_options: Moonbase::request_opts
      ) -> Moonbase::Collection

      def update: (
        String id,
        ?description: String,
        ?name: String,
        ?request_options: Moonbase::request_opts
      ) -> Moonbase::Collection

      def list: (
        ?after: String,
        ?before: String,
        ?limit: Integer,
        ?request_options: Moonbase::request_opts
      ) -> Moonbase::Internal::CursorPage[Moonbase::Models::CollectionListResponse]

      def initialize: (client: Moonbase::Client) -> void
    end
  end
end
