module Moonbase
  module Resources
    class Forms
      def retrieve: (
        String id,
        ?request_options: Moonbase::request_opts
      ) -> Moonbase::Form

      def list: (
        ?after: String,
        ?before: String,
        ?limit: Integer,
        ?request_options: Moonbase::request_opts
      ) -> Moonbase::Internal::CursorPage[Moonbase::Form]

      def initialize: (client: Moonbase::Client) -> void
    end
  end
end
