module Moonbase
  module Resources
    class InboxMessages
      attr_reader attachments: Moonbase::Resources::InboxMessages::Attachments

      def create: (
        body: Moonbase::FormattedText,
        inbox_id: String,
        ?bcc: ::Array[Moonbase::EmailMessageAddressParams],
        ?cc: ::Array[Moonbase::EmailMessageAddressParams],
        ?conversation_id: String,
        ?subject: String,
        ?to: ::Array[Moonbase::EmailMessageAddressParams],
        ?request_options: Moonbase::request_opts
      ) -> Moonbase::EmailMessage

      def retrieve: (
        String id,
        ?include: ::Array[Moonbase::Models::InboxMessageRetrieveParams::include_],
        ?request_options: Moonbase::request_opts
      ) -> Moonbase::EmailMessage

      def update: (
        String id,
        lock_version: Integer,
        ?bcc: ::Array[Moonbase::EmailMessageAddressParams],
        ?body: Moonbase::FormattedText,
        ?cc: ::Array[Moonbase::EmailMessageAddressParams],
        ?subject: String,
        ?to: ::Array[Moonbase::EmailMessageAddressParams],
        ?request_options: Moonbase::request_opts
      ) -> Moonbase::EmailMessage

      def list: (
        ?after: String,
        ?before: String,
        ?conversation_id: Moonbase::InboxMessageListParams::ConversationID,
        ?inbox_id: Moonbase::InboxMessageListParams::InboxID,
        ?limit: Integer,
        ?request_options: Moonbase::request_opts
      ) -> Moonbase::Internal::CursorPage[Moonbase::EmailMessagePointer]

      def delete: (String id, ?request_options: Moonbase::request_opts) -> nil

      def initialize: (client: Moonbase::Client) -> void
    end
  end
end
