module Moonbase
  module Resources
    class Inboxes
      def retrieve: (
        String id,
        ?include: Moonbase::Models::InboxRetrieveParams::include_,
        ?request_options: Moonbase::request_opts
      ) -> Moonbase::Inbox

      def list: (
        ?after: String,
        ?before: String,
        ?include: Moonbase::Models::InboxListParams::include_,
        ?limit: Integer,
        ?request_options: Moonbase::request_opts
      ) -> Moonbase::Internal::CursorPage[Moonbase::Inbox]

      def initialize: (client: Moonbase::Client) -> void
    end
  end
end
