module Moonbase
  module Resources
    class Items
      def create: (
        collection_id: String,
        values: ::Hash[Symbol, Moonbase::Models::field_value?],
        ?request_options: Moonbase::request_opts
      ) -> Moonbase::Item

      def retrieve: (
        String id,
        ?request_options: Moonbase::request_opts
      ) -> Moonbase::Item

      def update: (
        String id,
        values: ::Hash[Symbol, Moonbase::Models::field_value?],
        ?update_many_strategy: Moonbase::Models::ItemUpdateParams::update_many_strategy,
        ?update_one_strategy: Moonbase::Models::ItemUpdateParams::update_one_strategy,
        ?request_options: Moonbase::request_opts
      ) -> Moonbase::Item

      def delete: (
        String id,
        ?request_options: Moonbase::request_opts
      ) -> Moonbase::Item

      def upsert: (
        collection_id: String,
        identifiers: ::Hash[Symbol, Moonbase::Models::field_value?],
        values: ::Hash[Symbol, Moonbase::Models::field_value?],
        ?update_many_strategy: Moonbase::Models::ItemUpsertParams::update_many_strategy,
        ?update_one_strategy: Moonbase::Models::ItemUpsertParams::update_one_strategy,
        ?request_options: Moonbase::request_opts
      ) -> Moonbase::Item

      def initialize: (client: Moonbase::Client) -> void
    end
  end
end
