module Moonbase
  module Resources
    class Notes
      def create: (
        body: Moonbase::FormattedText,
        ?associations: ::Array[Moonbase::Pointer],
        ?request_options: Moonbase::request_opts
      ) -> Moonbase::Note

      def retrieve: (
        String id,
        ?request_options: Moonbase::request_opts
      ) -> Moonbase::Note

      def update: (
        String id,
        body: Moonbase::FormattedText,
        lock_version: Integer,
        ?request_options: Moonbase::request_opts
      ) -> Moonbase::Note

      def list: (
        ?after: String,
        ?before: String,
        ?limit: Integer,
        ?request_options: Moonbase::request_opts
      ) -> Moonbase::Internal::CursorPage[Moonbase::Note]

      def initialize: (client: Moonbase::Client) -> void
    end
  end
end
