module Moonbase
  module Resources
    class ProgramMessages
      def send_: (
        person: Moonbase::ProgramMessageSendParams::Person,
        program_template_id: String,
        ?custom_variables: ::Hash[Symbol, top],
        ?request_options: Moonbase::request_opts
      ) -> Moonbase::Models::ProgramMessageSendResponse

      def initialize: (client: Moonbase::Client) -> void
    end
  end
end
