module Moonbase
  module Resources
    class ProgramMessages
      def create: (
        person: Moonbase::ProgramMessageCreateParams::Person,
        program_template_id: String,
        ?custom_variables: ::Hash[Symbol, top],
        ?request_options: Moonbase::request_opts
      ) -> Moonbase::Models::ProgramMessageCreateResponse

      def initialize: (client: Moonbase::Client) -> void
    end
  end
end
