module Moonbase
  module Resources
    class Views
      attr_reader items: Moonbase::Resources::Views::Items

      def retrieve: (
        String id,
        ?include: ::Array[Moonbase::Models::ViewRetrieveParams::include_],
        ?request_options: Moonbase::request_opts
      ) -> Moonbase::View

      def initialize: (client: Moonbase::Client) -> void
    end
  end
end
