module MoonbaseSDK
  module Internal
    module Type
      module Union
        include MoonbaseSDK::Internal::Type::Converter
        include MoonbaseSDK::Internal::Util::SorbetRuntimeSupport

        private def self.known_variants: -> ::Array[[Symbol?, (^-> MoonbaseSDK::Internal::Type::Converter::input)]]

        def self.derefed_variants: -> ::Array[[Symbol?, top]]

        def self.variants: -> ::Array[top]

        private def self.discriminator: (Symbol property) -> void

        private def self.variant: (
          Symbol
          | ::Hash[Symbol, top]
          | ^-> MoonbaseSDK::Internal::Type::Converter::input
          | MoonbaseSDK::Internal::Type::Converter::input key,
          ?::Hash[Symbol, top]
          | ^-> MoonbaseSDK::Internal::Type::Converter::input
          | MoonbaseSDK::Internal::Type::Converter::input spec
        ) -> void

        private def self.resolve_variant: (
          top value
        ) -> MoonbaseSDK::Internal::Type::Converter::input?

        def ===: (top other) -> bool

        def ==: (top other) -> bool

        def hash: -> Integer

        def coerce: (
          top value,
          state: MoonbaseSDK::Internal::Type::Converter::coerce_state
        ) -> top

        def dump: (
          top value,
          state: MoonbaseSDK::Internal::Type::Converter::dump_state
        ) -> top

        def to_sorbet_type: -> top

        def inspect: (?depth: Integer) -> String
      end
    end
  end
end
