module Moonbase
  module Resources
    class Views
      class Items
        def list: (
          String id,
          ?after: String,
          ?before: String,
          ?limit: Integer,
          ?request_options: Moonbase::request_opts
        ) -> Moonbase::Internal::CursorPage[Moonbase::Item]

        def initialize: (client: Moonbase::Client) -> void
      end
    end
  end
end
