module MoonbaseSDK
  module Models
    module Collections
      type field_retrieve_params =
        { collection_id: String }
        & MoonbaseSDK::Internal::Type::request_parameters

      class FieldRetrieveParams < MoonbaseSDK::Internal::Type::BaseModel
        extend MoonbaseSDK::Internal::Type::RequestParameters::Converter
        include MoonbaseSDK::Internal::Type::RequestParameters

        attr_accessor collection_id: String

        def initialize: (
          collection_id: String,
          ?request_options: MoonbaseSDK::request_opts
        ) -> void

        def to_hash: -> {
          collection_id: String,
          request_options: MoonbaseSDK::RequestOptions
        }
      end
    end
  end
end
