module Moonbase
  class Client < Moonbase::Internal::Transport::BaseClient
    DEFAULT_MAX_RETRIES: 2

    DEFAULT_TIMEOUT_IN_SECONDS: Float

    DEFAULT_INITIAL_RETRY_DELAY: Float

    DEFAULT_MAX_RETRY_DELAY: Float

    attr_reader api_key: String

    attr_reader funnels: Moonbase::Resources::Funnels

    attr_reader collections: Moonbase::Resources::Collections

    attr_reader items: Moonbase::Resources::Items

    attr_reader views: Moonbase::Resources::Views

    attr_reader inboxes: Moonbase::Resources::Inboxes

    attr_reader inbox_conversations: Moonbase::Resources::InboxConversations

    attr_reader inbox_messages: Moonbase::Resources::InboxMessages

    attr_reader tagsets: Moonbase::Resources::Tagsets

    attr_reader programs: Moonbase::Resources::Programs

    attr_reader program_templates: Moonbase::Resources::ProgramTemplates

    attr_reader program_messages: Moonbase::Resources::ProgramMessages

    attr_reader forms: Moonbase::Resources::Forms

    attr_reader activities: Moonbase::Resources::Activities

    attr_reader calls: Moonbase::Resources::Calls

    attr_reader files: Moonbase::Resources::Files

    attr_reader meetings: Moonbase::Resources::Meetings

    attr_reader notes: Moonbase::Resources::Notes

    attr_reader webhook_endpoints: Moonbase::Resources::WebhookEndpoints

    attr_reader agent_settings: Moonbase::Resources::AgentSettings

    private def auth_headers: -> ::Hash[String, String]

    def initialize: (
      ?api_key: String?,
      ?base_url: String?,
      ?max_retries: Integer,
      ?timeout: Float,
      ?initial_retry_delay: Float,
      ?max_retry_delay: Float
    ) -> void
  end
end
