module MoonbaseSDK
  module Models
    type call_create_params =
      {
        direction: MoonbaseSDK::Models::CallCreateParams::direction,
        participants: ::Array[MoonbaseSDK::CallCreateParams::Participant],
        provider: String,
        provider_id: String,
        start_at: Time,
        status: MoonbaseSDK::Models::CallCreateParams::status,
        answered_at: Time,
        end_at: Time,
        provider_metadata: ::Hash[Symbol, top]
      }
      & MoonbaseSDK::Internal::Type::request_parameters

    class CallCreateParams < MoonbaseSDK::Internal::Type::BaseModel
      extend MoonbaseSDK::Internal::Type::RequestParameters::Converter
      include MoonbaseSDK::Internal::Type::RequestParameters

      attr_accessor direction: MoonbaseSDK::Models::CallCreateParams::direction

      attr_accessor participants: ::Array[MoonbaseSDK::CallCreateParams::Participant]

      attr_accessor provider: String

      attr_accessor provider_id: String

      attr_accessor start_at: Time

      attr_accessor status: MoonbaseSDK::Models::CallCreateParams::status

      attr_reader answered_at: Time?

      def answered_at=: (Time) -> Time

      attr_reader end_at: Time?

      def end_at=: (Time) -> Time

      attr_reader provider_metadata: ::Hash[Symbol, top]?

      def provider_metadata=: (::Hash[Symbol, top]) -> ::Hash[Symbol, top]

      def initialize: (
        direction: MoonbaseSDK::Models::CallCreateParams::direction,
        participants: ::Array[MoonbaseSDK::CallCreateParams::Participant],
        provider: String,
        provider_id: String,
        start_at: Time,
        status: MoonbaseSDK::Models::CallCreateParams::status,
        ?answered_at: Time,
        ?end_at: Time,
        ?provider_metadata: ::Hash[Symbol, top],
        ?request_options: MoonbaseSDK::request_opts
      ) -> void

      def to_hash: -> {
        direction: MoonbaseSDK::Models::CallCreateParams::direction,
        participants: ::Array[MoonbaseSDK::CallCreateParams::Participant],
        provider: String,
        provider_id: String,
        start_at: Time,
        status: MoonbaseSDK::Models::CallCreateParams::status,
        answered_at: Time,
        end_at: Time,
        provider_metadata: ::Hash[Symbol, top],
        request_options: MoonbaseSDK::RequestOptions
      }

      type direction = :incoming | :outgoing

      module Direction
        extend MoonbaseSDK::Internal::Type::Enum

        INCOMING: :incoming
        OUTGOING: :outgoing

        def self?.values: -> ::Array[MoonbaseSDK::Models::CallCreateParams::direction]
      end

      type participant =
        {
          phone: String,
          role: MoonbaseSDK::Models::CallCreateParams::Participant::role
        }

      class Participant < MoonbaseSDK::Internal::Type::BaseModel
        attr_accessor phone: String

        attr_accessor role: MoonbaseSDK::Models::CallCreateParams::Participant::role

        def initialize: (
          phone: String,
          role: MoonbaseSDK::Models::CallCreateParams::Participant::role
        ) -> void

        def to_hash: -> {
          phone: String,
          role: MoonbaseSDK::Models::CallCreateParams::Participant::role
        }

        type role = :caller | :callee | :other

        module Role
          extend MoonbaseSDK::Internal::Type::Enum

          CALLER: :caller
          CALLEE: :callee
          OTHER: :other

          def self?.values: -> ::Array[MoonbaseSDK::Models::CallCreateParams::Participant::role]
        end
      end

      type status =
        :queued
        | :initiated
        | :ringing
        | :in_progress
        | :completed
        | :busy
        | :failed
        | :no_answer
        | :canceled
        | :missed
        | :answered
        | :forwarded
        | :abandoned

      module Status
        extend MoonbaseSDK::Internal::Type::Enum

        QUEUED: :queued
        INITIATED: :initiated
        RINGING: :ringing
        IN_PROGRESS: :in_progress
        COMPLETED: :completed
        BUSY: :busy
        FAILED: :failed
        NO_ANSWER: :no_answer
        CANCELED: :canceled
        MISSED: :missed
        ANSWERED: :answered
        FORWARDED: :forwarded
        ABANDONED: :abandoned

        def self?.values: -> ::Array[MoonbaseSDK::Models::CallCreateParams::status]
      end
    end
  end
end
