module MoonbaseSDK
  module Models
    type field_value =
      MoonbaseSDK::SingleLineTextValue
      | MoonbaseSDK::MultiLineTextValue
      | MoonbaseSDK::IntegerValue
      | MoonbaseSDK::FloatValue
      | MoonbaseSDK::MonetaryValue
      | MoonbaseSDK::PercentageValue
      | MoonbaseSDK::BooleanValue
      | MoonbaseSDK::EmailValue
      | MoonbaseSDK::URLValue
      | MoonbaseSDK::DomainValue
      | MoonbaseSDK::SocialXValue
      | MoonbaseSDK::SocialLinkedInValue
      | MoonbaseSDK::TelephoneNumber
      | MoonbaseSDK::GeoValue
      | MoonbaseSDK::DateValue
      | MoonbaseSDK::DatetimeValue
      | MoonbaseSDK::Choice
      | MoonbaseSDK::FunnelStep
      | MoonbaseSDK::RelationValue
      | ::Array[MoonbaseSDK::Models::value]

    module FieldValue
      extend MoonbaseSDK::Internal::Type::Union

      def self?.variants: -> ::Array[MoonbaseSDK::Models::field_value]

      ValueArray: MoonbaseSDK::Internal::Type::Converter
    end
  end
end
