module MoonbaseSDK
  module Models
    type item_create_params =
      {  } & MoonbaseSDK::Internal::Type::request_parameters

    class ItemCreateParams < MoonbaseSDK::Models::ItemCreateParams
      extend MoonbaseSDK::Internal::Type::RequestParameters::Converter
      include MoonbaseSDK::Internal::Type::RequestParameters

      def initialize: (?request_options: MoonbaseSDK::request_opts) -> void

      def to_hash: -> { request_options: MoonbaseSDK::RequestOptions }
    end
  end
end
