module MoonbaseSDK
  module Models
    type item_create_params =
      {
        collection_id: String,
        values: ::Hash[Symbol, MoonbaseSDK::Models::field_value?]
      }
      & MoonbaseSDK::Internal::Type::request_parameters

    class ItemCreateParams < MoonbaseSDK::Internal::Type::BaseModel
      extend MoonbaseSDK::Internal::Type::RequestParameters::Converter
      include MoonbaseSDK::Internal::Type::RequestParameters

      attr_accessor collection_id: String

      attr_accessor values: ::Hash[Symbol, MoonbaseSDK::Models::field_value?]

      def initialize: (
        collection_id: String,
        values: ::Hash[Symbol, MoonbaseSDK::Models::field_value?],
        ?request_options: MoonbaseSDK::request_opts
      ) -> void

      def to_hash: -> {
        collection_id: String,
        values: ::Hash[Symbol, MoonbaseSDK::Models::field_value?],
        request_options: MoonbaseSDK::RequestOptions
      }
    end
  end
end
