module MoonbaseSDK
  module Models
    type program_template_retrieve_params =
      {
        include: ::Array[MoonbaseSDK::Models::ProgramTemplateRetrieveParams::include_]
      }
      & MoonbaseSDK::Internal::Type::request_parameters

    class ProgramTemplateRetrieveParams < MoonbaseSDK::Internal::Type::BaseModel
      extend MoonbaseSDK::Internal::Type::RequestParameters::Converter
      include MoonbaseSDK::Internal::Type::RequestParameters

      attr_reader include: ::Array[MoonbaseSDK::Models::ProgramTemplateRetrieveParams::include_]?

      def include=: (
        ::Array[MoonbaseSDK::Models::ProgramTemplateRetrieveParams::include_]
      ) -> ::Array[MoonbaseSDK::Models::ProgramTemplateRetrieveParams::include_]

      def initialize: (
        ?include: ::Array[MoonbaseSDK::Models::ProgramTemplateRetrieveParams::include_],
        ?request_options: MoonbaseSDK::request_opts
      ) -> void

      def to_hash: -> {
        include: ::Array[MoonbaseSDK::Models::ProgramTemplateRetrieveParams::include_],
        request_options: MoonbaseSDK::RequestOptions
      }

      type include_ = :program

      module Include
        extend MoonbaseSDK::Internal::Type::Enum

        PROGRAM: :program

        def self?.values: -> ::Array[MoonbaseSDK::Models::ProgramTemplateRetrieveParams::include_]
      end
    end
  end
end
