module MoonbaseSDK
  module Models
    type relation_value = { item: MoonbaseSDK::Item, type: :"value/relation" }

    class RelationValue < MoonbaseSDK::Internal::Type::BaseModel
      attr_accessor item: MoonbaseSDK::Item

      attr_accessor type: :"value/relation"

      def initialize: (
        item: MoonbaseSDK::Item,
        ?type: :"value/relation"
      ) -> void

      def to_hash: -> { item: MoonbaseSDK::Item, type: :"value/relation" }
    end
  end
end
