module MoonbaseSDK
  module Resources
    class Forms
      def retrieve: (
        String id,
        ?include: ::Array[MoonbaseSDK::Models::FormRetrieveParams::include_],
        ?request_options: MoonbaseSDK::request_opts
      ) -> MoonbaseSDK::Form

      def list: (
        ?after: String,
        ?before: String,
        ?include: ::Array[MoonbaseSDK::Models::FormListParams::include_],
        ?limit: Integer,
        ?request_options: MoonbaseSDK::request_opts
      ) -> MoonbaseSDK::Internal::CursorPage[MoonbaseSDK::Form]

      def initialize: (client: MoonbaseSDK::Client) -> void
    end
  end
end
