module MoonbaseSDK
  module Resources
    class Meetings
      def retrieve: (
        String id,
        ?include: ::Array[MoonbaseSDK::Models::MeetingRetrieveParams::include_],
        ?request_options: MoonbaseSDK::request_opts
      ) -> MoonbaseSDK::Meeting

      def list: (
        ?after: String,
        ?before: String,
        ?limit: Integer,
        ?request_options: MoonbaseSDK::request_opts
      ) -> MoonbaseSDK::Internal::CursorPage[MoonbaseSDK::Meeting]

      def initialize: (client: MoonbaseSDK::Client) -> void
    end
  end
end
