module MoonbaseSDK
  module Resources
    class ProgramMessages
      def create: (
        person: MoonbaseSDK::ProgramMessageCreateParams::Person,
        program_template_id: String,
        ?custom_variables: ::Hash[Symbol, top],
        ?request_options: MoonbaseSDK::request_opts
      ) -> MoonbaseSDK::Models::ProgramMessageCreateResponse

      def initialize: (client: MoonbaseSDK::Client) -> void
    end
  end
end
