module MoonbaseSDK
  module Resources
    class ProgramTemplates
      def retrieve: (
        String id,
        ?include: ::Array[MoonbaseSDK::Models::ProgramTemplateRetrieveParams::include_],
        ?request_options: MoonbaseSDK::request_opts
      ) -> MoonbaseSDK::ProgramTemplate

      def list: (
        ?after: String,
        ?before: String,
        ?include: ::Array[MoonbaseSDK::Models::ProgramTemplateListParams::include_],
        ?limit: Integer,
        ?request_options: MoonbaseSDK::request_opts
      ) -> MoonbaseSDK::Internal::CursorPage[MoonbaseSDK::ProgramTemplate]

      def initialize: (client: MoonbaseSDK::Client) -> void
    end
  end
end
