module MoonbaseSDK
  module Resources
    class Views
      def retrieve: (
        String id,
        ?include: ::Array[MoonbaseSDK::Models::ViewRetrieveParams::include_],
        ?request_options: MoonbaseSDK::request_opts
      ) -> MoonbaseSDK::View

      def list_items: (
        String id,
        ?after: String,
        ?before: String,
        ?limit: Integer,
        ?request_options: MoonbaseSDK::request_opts
      ) -> MoonbaseSDK::Internal::CursorPage[MoonbaseSDK::Item]

      def initialize: (client: MoonbaseSDK::Client) -> void
    end
  end
end
