module Moonbase
  module Resources
    class Collections
      class Fields
        def retrieve: (
          String id,
          collection_id: String,
          ?request_options: Moonbase::request_opts
        ) -> Moonbase::Models::field

        def initialize: (client: Moonbase::Client) -> void
      end
    end
  end
end
