module Moonbase
  module Resources
    class Collections
      class Items
        def create: (
          String collection_id,
          values: ::Hash[Symbol, Moonbase::Models::field_value_param?],
          ?request_options: Moonbase::request_opts
        ) -> Moonbase::Item

        def retrieve: (
          String id,
          collection_id: String,
          ?request_options: Moonbase::request_opts
        ) -> Moonbase::Item

        def update: (
          String id,
          collection_id: String,
          values: ::Hash[Symbol, Moonbase::Models::field_value_param?],
          ?update_many_strategy: Moonbase::Models::Collections::ItemUpdateParams::update_many_strategy,
          ?update_one_strategy: Moonbase::Models::Collections::ItemUpdateParams::update_one_strategy,
          ?request_options: Moonbase::request_opts
        ) -> Moonbase::Item

        def list: (
          String collection_id,
          ?after: String,
          ?before: String,
          ?limit: Integer,
          ?request_options: Moonbase::request_opts
        ) -> Moonbase::Internal::CursorPage[Moonbase::Item]

        def delete: (
          String id,
          collection_id: String,
          ?request_options: Moonbase::request_opts
        ) -> nil

        def upsert: (
          String collection_id,
          identifiers: ::Hash[Symbol, Moonbase::Models::field_value_param?],
          values: ::Hash[Symbol, Moonbase::Models::field_value_param?],
          ?update_many_strategy: Moonbase::Models::Collections::ItemUpsertParams::update_many_strategy,
          ?update_one_strategy: Moonbase::Models::Collections::ItemUpsertParams::update_one_strategy,
          ?request_options: Moonbase::request_opts
        ) -> Moonbase::Item

        def initialize: (client: Moonbase::Client) -> void
      end
    end
  end
end
