# frozen_string_literal: true

# Standard libraries.
# rubocop:disable Lint/RedundantRequireStatement
require "English"
require "cgi"
require "date"
require "erb"
require "etc"
require "json"
require "net/http"
require "pathname"
require "rbconfig"
require "securerandom"
require "set"
require "stringio"
require "time"
require "uri"
# rubocop:enable Lint/RedundantRequireStatement

# We already ship the preferred sorbet manifests in the package itself.
# `tapioca` currently does not offer us a way to opt out of unnecessary compilation.
if Object.const_defined?(:Tapioca) &&
   caller.chain([$PROGRAM_NAME]).chain(ARGV).any?(/tapioca/) &&
   ARGV.none?(/dsl/)
  return
end

# Gems.
require "connection_pool"

# Package files.
require_relative "moonbase_sdk/version"
require_relative "moonbase_sdk/internal/util"
require_relative "moonbase_sdk/internal/type/converter"
require_relative "moonbase_sdk/internal/type/unknown"
require_relative "moonbase_sdk/internal/type/boolean"
require_relative "moonbase_sdk/internal/type/file_input"
require_relative "moonbase_sdk/internal/type/enum"
require_relative "moonbase_sdk/internal/type/union"
require_relative "moonbase_sdk/internal/type/array_of"
require_relative "moonbase_sdk/internal/type/hash_of"
require_relative "moonbase_sdk/internal/type/base_model"
require_relative "moonbase_sdk/internal/type/base_page"
require_relative "moonbase_sdk/internal/type/request_parameters"
require_relative "moonbase_sdk/internal"
require_relative "moonbase_sdk/request_options"
require_relative "moonbase_sdk/file_part"
require_relative "moonbase_sdk/errors"
require_relative "moonbase_sdk/internal/transport/base_client"
require_relative "moonbase_sdk/internal/transport/pooled_net_requester"
require_relative "moonbase_sdk/client"
require_relative "moonbase_sdk/internal/cursor_page"
require_relative "moonbase_sdk/models/boolean_value"
require_relative "moonbase_sdk/models/call"
require_relative "moonbase_sdk/models/call_create_params"
require_relative "moonbase_sdk/models/choice"
require_relative "moonbase_sdk/models/collection"
require_relative "moonbase_sdk/models/collection_list_params"
require_relative "moonbase_sdk/models/collection_retrieve_params"
require_relative "moonbase_sdk/models/collections/field_retrieve_params"
require_relative "moonbase_sdk/models/datetime_value"
require_relative "moonbase_sdk/models/date_value"
require_relative "moonbase_sdk/models/domain_value"
require_relative "moonbase_sdk/models/email_value"
require_relative "moonbase_sdk/models/error"
require_relative "moonbase_sdk/models/field"
require_relative "moonbase_sdk/models/field_value"
require_relative "moonbase_sdk/models/float_value"
require_relative "moonbase_sdk/models/funnel_step"
require_relative "moonbase_sdk/models/geo_value"
require_relative "moonbase_sdk/models/integer_value"
require_relative "moonbase_sdk/models/item"
require_relative "moonbase_sdk/models/item_create_params"
require_relative "moonbase_sdk/models/item_delete_params"
require_relative "moonbase_sdk/models/item_retrieve_params"
require_relative "moonbase_sdk/models/item_update_params"
require_relative "moonbase_sdk/models/item_upsert_params"
require_relative "moonbase_sdk/models/monetary_value"
require_relative "moonbase_sdk/models/multi_line_text_value"
require_relative "moonbase_sdk/models/percentage_value"
require_relative "moonbase_sdk/models/relation_value"
require_relative "moonbase_sdk/models/single_line_text_value"
require_relative "moonbase_sdk/models/social_linked_in_value"
require_relative "moonbase_sdk/models/social_x_value"
require_relative "moonbase_sdk/models/telephone_number"
require_relative "moonbase_sdk/models/url_value"
require_relative "moonbase_sdk/models/value"
require_relative "moonbase_sdk/models/view"
require_relative "moonbase_sdk/models"
require_relative "moonbase_sdk/resources/calls"
require_relative "moonbase_sdk/resources/collections"
require_relative "moonbase_sdk/resources/collections/fields"
require_relative "moonbase_sdk/resources/items"
