module Moonbase
  module Models
    module Collections
      type item_retrieve_params =
        { collection_id: String } & Moonbase::Internal::Type::request_parameters

      class ItemRetrieveParams < Moonbase::Internal::Type::BaseModel
        extend Moonbase::Internal::Type::RequestParameters::Converter
        include Moonbase::Internal::Type::RequestParameters

        attr_accessor collection_id: String

        def initialize: (
          collection_id: String,
          ?request_options: Moonbase::request_opts
        ) -> void

        def to_hash: -> {
          collection_id: String,
          request_options: Moonbase::RequestOptions
        }
      end
    end
  end
end
