module Moonbase
  module Internal
    class CursorPage[Elem]
      include Moonbase::Internal::Type::BasePage[Elem]

      attr_accessor data: ::Array[Elem]?

      attr_accessor meta: Meta

      def inspect: -> String

      type meta = { cursors: Meta::Cursors }
      class Meta < Moonbase::Internal::Type::BaseModel
        attr_reader cursors: Meta::Cursors?

        def cursors=: (Meta::Cursors) -> Meta::Cursors

        def initialize: (?cursors: Meta::Cursors) -> void

        def to_hash: -> { cursors: Meta::Cursors }

        type cursors = { next_: String }

        class Cursors < Moonbase::Internal::Type::BaseModel
          attr_reader next_: String?

          def next_=: (String) -> String

          def initialize: (?next_: String) -> void

          def to_hash: -> { next_: String }
        end
      end
    end
  end
end
