module MoonbaseSDK
  class Client < MoonbaseSDK::Internal::Transport::BaseClient
    DEFAULT_MAX_RETRIES: 2

    DEFAULT_TIMEOUT_IN_SECONDS: Float

    DEFAULT_INITIAL_RETRY_DELAY: Float

    DEFAULT_MAX_RETRY_DELAY: Float

    attr_reader api_key: String

    attr_reader calls: MoonbaseSDK::Resources::Calls

    attr_reader collections: MoonbaseSDK::Resources::Collections

    attr_reader files: MoonbaseSDK::Resources::Files

    attr_reader forms: MoonbaseSDK::Resources::Forms

    attr_reader inbox_conversations: MoonbaseSDK::Resources::InboxConversations

    attr_reader inbox_messages: MoonbaseSDK::Resources::InboxMessages

    attr_reader inboxes: MoonbaseSDK::Resources::Inboxes

    attr_reader items: MoonbaseSDK::Resources::Items

    attr_reader meetings: MoonbaseSDK::Resources::Meetings

    attr_reader notes: MoonbaseSDK::Resources::Notes

    attr_reader program_messages: MoonbaseSDK::Resources::ProgramMessages

    attr_reader program_templates: MoonbaseSDK::Resources::ProgramTemplates

    attr_reader programs: MoonbaseSDK::Resources::Programs

    attr_reader tagsets: MoonbaseSDK::Resources::Tagsets

    attr_reader views: MoonbaseSDK::Resources::Views

    private def auth_headers: -> ::Hash[String, String]

    def initialize: (
      ?api_key: String?,
      ?base_url: String?,
      ?max_retries: Integer,
      ?timeout: Float,
      ?initial_retry_delay: Float,
      ?max_retry_delay: Float
    ) -> void
  end
end
