module MoonbaseSDK
  class Error = MoonbaseSDK::Models::Error

  class Program = MoonbaseSDK::Models::Program

  class ProgramListParams = MoonbaseSDK::Models::ProgramListParams

  class ProgramMessageSendParams = MoonbaseSDK::Models::ProgramMessageSendParams

  class ProgramRetrieveParams = MoonbaseSDK::Models::ProgramRetrieveParams

  class ProgramTemplate = MoonbaseSDK::Models::ProgramTemplate

  class ProgramTemplateListParams = MoonbaseSDK::Models::ProgramTemplateListParams

  class ProgramTemplateRetrieveParams = MoonbaseSDK::Models::ProgramTemplateRetrieveParams
end
